@extends('layouts.help')
@section('title', 'Términos y Condiciones')
@section('first', 'Términos y Condiciones')
@section('second', 'Nuestros Términos Legales y Política de Privacidad')
@section('content')
<div class="box">
  <div class="right">
    <a href="{{ url('/terms') }}">EN</a>
    <a href="{{ url('/terms_es') }}" class="active">ES</a>
  </div>
  <div class="box-body">
      <strong>Al aceptar los términos y condiciones de uso entiendes que:</strong>
      <ul>
        <li><strong>1.</strong> Los usuarios siempre deben consultar las leyes locales y nacionales de cada país relativas a la prestación de diferentes clases de servicios y se abstendrá de utilizar la plataforma para realizar actividades ilegales.</li>
        <li><strong>2.</strong> Los usuarios no podrán hacer reclamación alguna contra Migohood, sino contra el usuario que haya causado con sus acciones u omisiones un perjuicio.</li>
        <li><strong>3.</strong> La plataforma respetara las diferencias de sexo, raza, origen nacional o familiar, lengua, religión, opinión política o filosófica y ofrecerá el mismo trato sin ninguna discriminación por razones de sexo, raza, origen nacional o familiar, lengua, religión, opinión política o filosófica.</li>
        <li><strong>4.</strong> Migohood se reserva el derecho a se reserva el derecho a modificar la página, la aplicación o los servicios, y modificar  los términos y condiciones de uso, incluidas las tarifas de  los servicios, en cualquier momento y sin previo aviso.  Las modificaciones serán publicadas en la plataforma o por cualquier otro medio. Si el usuario continúa usando y accediendo a la plataforma una vez publicada la modificación, el usuario se entiende que acepta estar continuar registrado en la página o aplicación Si no acepta los términos y condiciones de uso, puede dejar de utilizar la plataforma o cerrar su perfil.</li>
        <li><strong>5.</strong> Solo pueden registrarse como usuarios mayores de 18 años.</li>
        <li><strong>6.</strong> Para ofrecer un servicio o realizar una reserva debes estar registrado en la plataforma.</li>
        <li><strong>7.</strong> Migohood no es propietaria ni operadora de bienes inmuebles ni muebles que sean utilizados en la prestación de servicios que sean ofrecidos en la plataforma ni tampoco actúa como agente de propietarios ni operadores de bienes inmuebles o muebles utilizados en la prestación de servicios que sean ofrecidos en la plataforma.</li>
        <li><strong>8.</strong> Migohood facilita la disponibilidad de la página web, la aplicación y servicios relacionados y  actúa como agente de cobros limitado de cada usuario.</li>
        <li><strong>9.</strong> Migohood no será responsable por  el contenido que los usuarios publiquen a través de sus perfiles.</li>
        <li><strong>10.</strong> Migohood  no es responsable por las  reservas que se realicen o se acepten a través de esta plataforma. Es absoluta responsabilidad de los usuarios. De igual manera serán los usuarios los únicos responsables por sus actos u omisiones al antes durante y después  de la prestación de servicios entre ellos.</li>
        <li><strong>11.</strong> Migohood no es responsable de ningún daño o lesión que resulte de las interacciones entre usuarios.</li>
        <li><strong>12.</strong> Migohood recomienda que los usuarios contraten un seguro adecuado para sus servicios y ofrece asesorías relativas al tema según cada país.</li>
        <li><strong>13.</strong> Migohood puede ofrecer a los usuarios la opción de que un fotógrafo realice fotos de sus servicios y de esta manera verificar través de Migohood las imágenes de su perfil. Todas las imágenes tomadas por los fotógrafos de Migohood serán propiedad de Migohood y podrán ser usados por la empresa para fines comerciales entre otros.</li>
        <li><strong>14.</strong> Todos los usuarios pueden donar la cantidad de dinero que elijan, estas donaciones se transferirán a la Fundación de Migohood, la cual tiene entre sus fines promover el desarrollo social y empresarial de aquellos emprendedores dispuestos a innovar y de la comunidad en general y generar beneficios para la comunidad en general en diversos ordenes como en lo cultural, lo recreativo, lo deportivo entre otros</li>
      </ul>

    <h4>Conducta de los usuarios.</h4>
    Usted acepta y conviene que asume toda la responsabilidad de cumplir con las leyes, reglamentos y normativas, así como con las obligaciones fiscales que sean aplicables al uso que realice de la página web, la aplicación, los servicios y los contenidos. En conexión con su uso de la página web, la aplicación, los servicios y los contenidos, usted no puede y acepta que usted no:
    infringirá ninguna ley o norma local, estatal, provincial, nacional o de otro tipo, ni ninguna orden judicial, incluyendo, sin limitación, las restricciones urbanísticas y los reglamentos tributarios;
    utilizará programas informáticos, dispositivos, robots, backdoors u otros medios o procesos manuales o automáticos a fin de acceder, extraer, recopilar o analizar contenido de cualquier página web u otro servicio alojado en la página web, en la aplicación, en los servicios, o en los contenidos colectivos;
        accederá o utilizará nuestra página web, aplicación, servicios o el API de Migohood para usar, exponer o permitir que se use o se exponga, cualquier contenido de Migohood que no sea públicamente mostrado por Migohood en sus páginas de resultados de búsqueda o páginas de alojamientos y servicios antes de la confirmación de una reserva; sea incoherente de alguna manera con la política de privacidad de Migohood o las condiciones del servicio; o infrinja de otro modo los derechos de privacidad o cualesquiera otros derechos de los usuarios de Migohood o de cualquier tercero;
    utilizará la página web, la aplicación, los servicios o los contenidos colectivos para fines comerciales o de otro tipo que no estén explícitamente autorizados en los presentes términos;
    copiará, almacenará, accederá o utilizará de otro modo cualquier información albergada en la página web, la aplicación, los servicios o los contenidos colectivos para fines que no estén explícitamente autorizados en los presentes términos;
    infringirá los derechos de ninguna persona o entidad, incluyendo sin limitación, su propiedad intelectual, privacidad, publicidad o derechos contractuales;
    interferirá con, ni dañará, nuestra página web, aplicación o servicios, incluyendo sin limitación, a través del uso de virus, robots de cancelación, caballos troyanos, código malicioso, invasión de paquetes, ataques por denegación de servicio, backdoors, suplantación de paquetes o de IP, rutas falsificadas o información de dirección de correo electrónico o métodos o tecnología similares;
    utilizará nuestra página web, aplicación o servicios para transmitir, distribuir, publicar o entregar ninguna información relacionada con ninguna otra persona o entidad, incluyendo sin limitación, fotografías de otros sin su permiso, información de contacto personal o números de cuenta o tarjetas de crédito, de débito o de llamadas;
    utilizará nuestra página web, aplicación, servicios o contenidos colectivos en conexión con la distribución de correo electrónico comercial no solicitado ("Spam") o anuncios no relacionados con el alojamiento en una residencia particular;
    "asediará" ni acosará a ningún otro usuario de nuestra página web, aplicación, servicios o Contenidos colectivos ni recopilará ni almacenará ninguna información identificable personalmente sobre ningún otro usuario para propósitos distintos de transacciones como cliente o usuario de Migohood;
    ofrecerá, como usuario, ningún alojamiento que usted mismo no posea ni tenga permiso para alquilar como propiedad residencial u otras (sin limitación de lo anterior, usted no ofrecerá alojamientos como si fuera suyo si está actuando en la capacidad de agente de alquiler o agente de un tercero);
    ofrecerá, como usuario, ningún alojamiento que no pueda ser alquilado o subalquilado en relación con los términos y las condiciones de un acuerdo con un tercero, incluyendo, entre otros, un acuerdo de alquiler de propiedad;
    se registrará en más de una cuenta de Migohood o se registrará en una cuenta de Migohood en nombre de una persona distinta a usted mismo;
    salvo con el permiso expreso de Migohood, solicitará o reservará una estancia en un alojamiento si no es usted mismo quien se quedará en dicho alojamiento;
    se pondrá en contacto con un usuario por ningún motivo distinto a hacerle una pregunta relacionada con una reserva o los alojamientos y los servicios.
    se pondrá en contacto con un cliente por ningún motivo distinto a hacerle una pregunta relacionada con una reserva o con el uso de dicho cliente de la página web, aplicación y servicios;
    reclutará o de otra manera solicitará a cualquier usuario u otro miembro a incorporarse a servicios o páginas web de tercero que sean competencia de Migohood, sin la aprobación previa por escrito de Migohood;
    se hará pasar por ninguna persona o entidad, ni falsificará o de otra manera se representará falsamente a usted mismo o a su afiliación con cualquier persona o entidad;
    utilizará guiones automatizados para recopilar información ni de ninguna otra manera interactuará con la página web, la aplicación, los servicios o los contenidos colectivos;
    utilizará la página, la aplicación, los servicios o los contenidos colectivos para encontrar un usuario o un cliente y después realizará una reserva de un alojamiento independiente de la página, la aplicación o los servicios para evitar la obligación de pagar cualquier tarifa de servicio relacionado con la provisión de los servicios por parte de Migohood o para cualquier otro fin;
    presentará ninguna información falsa o engañosa sobre precios, ni  publicara un precio que no pretenda sostener o cumplir;
    colgará, cargará, publicará, enviará o transmitirá ningún contenido que: infrinja, se apropie o viole una patente, derecho de autor, marca comercial, secreto, derechos morales u otros derechos de propiedad intelectual de un tercero, o los derechos de publicidad o privacidad; viole, o anime cualquier conducta que violaría, cualquier ley o regulación aplicable o genere responsabilidad civil; sea fraudulento, falso, engañoso o falaz; sea difamatorio, obsceno, pornográfico, vulgar u ofensivo; promueva la discriminación, intolerancia, racismo, odio, acoso o daño contra cualquier persona o grupo; sea violento o amenazante o promueva la violencia o acciones que sean amenazantes para cualquier otra persona; o promueva actividades o sustancias ilegales o dañinas;
    recuperará sistemáticamente datos u otros contenidos de nuestra página web, aplicación o servicios para crear o recopilar, directa o indirectamente, en una sola o múltiples descargas, una colección, recopilación, base de datos, directorio o similar, ya sea por métodos manuales, utilizando robots, orugas o arañas, u otros;
    utilizará, mostrará, copiará o enmarcará la página web, la aplicación, los servicios o los contenidos colectivos ni ningún elemento individual de la página web, la aplicación, los servicios o los contenidos colectivos, el nombre de Migohood, cualquier marca registrada de Migohood, logotipo u otra información propietaria, o el diseño y la maquetación de cualquier página o formulario contenido en una página en la página web, la aplicación o los servicios, sin el consentimiento expreso por escrito de Migohood;
    accederá, manipulará ni utilizará áreas no públicas de la página web, la aplicación o los servicios, los sistemas de ordenadores de Migohood, ni los sistemas de entrega técnica de los proveedores de Migohood;
    intentará sondear, escanear o probar la vulnerabilidad de cualquier sistema o red de Migohood, ni infringirá ninguna medida de seguridad o autentificación;
    evitará, rodeará, retirará, desactivará, deshabilitará, desmontará ni de ninguna otra manera esquivará ninguna medida tecnológica aplicada por Mighood o cualquiera de los proveedores de Migohood u otro tercero (incluyendo otro usuario) para proteger la página web, los servicios, la aplicación o los contenidos colectivos;
    falsificará ninguna cabecera de paquetes TCP/IP ni ninguna parte de la información de cabecera de ningún correo electrónico ni publicación de grupos de noticias, ni de ninguna manera utilizará la página web, los servicios, la aplicación o los contenidos colectivos para enviar información alterada, engañosa o falsa que identifique la fuente;
    intentará descifrar, descompilar, desmontar o hacer ingeniería inversa de ningún software utilizado para ofrecer la página web, los servicios, la aplicación o los contenidos colectivos;
    defenderá, animará o ayudará a ningún tercero en hacer nada de lo anterior; o
    aceptará o efectuará un pago de las tarifas de alojamiento o servicio fuera de Migohood. Si lo realiza, usted reconoce y acepta que: estará incumpliendo las presentes condiciones; acepta todos los riesgos y la responsabilidad por dicho pago y eximirá a  Migohood de cualquier responsabilidad por dicho pago.
    Migohood tiene derecho a investigar y perseguir infracciones de cualquiera de los anteriores en todo lo que permita la ley.
    Migohood podrá acceder, preservar y revelar sus datos cuando así lo exija la ley, o cuando consideremos de buena fe que ello es razonablemente necesario para responder a reclamaciones presentadas contra Migohood,  o para cumplir con lo establecido en cualquier notificación procesal (por ejemplo, citaciones u órdenes judiciales), hacer cumplir o administrar nuestros acuerdos con los usuarios, tales como las presentes condiciones, o prevenir el fraude, evaluar riesgos, llevar a cabo investigaciones, prestar apoyo a clientes, desarrollar productos o realizar depuraciones, o  proteger los derechos, los bienes o la seguridad de Migohood, de sus usuarios o del público en general. Usted acepta que Migohood no tiene ninguna obligación de supervisar su acceso o uso de la página web, la aplicación, los servicios o los contenidos colectivos o de revisar o editar ningún contenido de los miembros, pero tiene el derecho de hacerlo con el propósito de hacer funcionar y mejorar la página web, la aplicación y los servicios (incluyendo, sin limitación alguna, con el fin de evitar actividades fraudulentas, evaluar riesgos, realizar investigaciones y prestar soporte al Cliente), asegurar su cumplimiento con estos términos, cumplir con la ley aplicable o la orden o el requisito de un tribunal, agencia administrativa u otro ente gubernamental, dar respuesta a contenido que considere cuestionable de algún modo o conforme a lo estipulado en estas condiciones. Migohood se reserva el derecho, en cualquier momento y sin aviso previo, de retirar o deshabilitar el acceso a cualquier contenido colectivo que Migohood, bajo su criterio exclusivo, considere que es cuestionable por cualquier motivo, infringe estos términos o de cualquier otra manera es dañino para la página web, la aplicación o los servicios.

    <h4>Sobre malas conductas.</h4>

    Si se aloja con, o acoge a alguien que usted cree que está actuando o ha actuado de manera inapropiada, incluyendo, entre otros, cualquier persona que se involucre en comportamiento ofensivo, violento o inapropiado sexualmente, sospeche que le ha robado, o se involucre en cualquier otra conducta indebida, debe informar inmediatamente de dicha persona a las autoridades correspondientes y después a Migohood poniéndose en contacto con  la autoridad de policía local; a condición de que su denuncia no nos obligará a tomar ninguna medida más allá de lo obligado por la ley, si la hay, ni hará que incurramos en ninguna responsabilidad hacia usted.

     <strong>EN CASO DE EMERGENCIA.</strong> Migohood envía mensajes de correo electrónico de forma automática a los usuarios del lugar en cuestión. Los usuarios también pueden tratar de comunicarse con otros usuarios que se encuentren en el lugar afectado, según la clase de emergencia. Los usuarios podrán alojar  y prestar servicios a otros usuarios gratis durante la duración de la emergencia.
    Se aconseja llamar a las autoridades locales como bomberos, policías, ambulancias, hospitales y cualquier clase de centro de atención ciudadana, y las embajadas y consulados de sus países de origen, según el caso.

    <h4>Sobre los Términos Financieros.</h4>

    Tarifa de alojamiento o servicio del usuario: cantidades que debe pagar un  usuario -cliente a cambio de su estancia en un alojamiento o por la prestación de un servicio. Es el  usuario-anfitrión exclusivamente, y no Migohood el responsable de las tarifas de alojamiento que ofrece. El usuario- anfitrión puede decidir de manera exclusiva, que estas cantidades incluyan una tarifa de limpieza o cualquier otra tarifa permitida en la plataforma de Migohood, u otros valores que el usuario anfitrión determine que debe cobrar.
    Tarifa de cliente: tarifa que Migohood cobra a un usuario-cliente por el uso de los servicios basándose en un porcentaje de las tarifas de alojamiento o servicio aplicables. Las tarifas de cliente serán mostradas al usuario-cliente cuando se le pregunte si desea enviar una solicitud de reserva a un usuario-anfitrión.
    Tarifa de usuario: tarifa que Migohood cobra a un usuario-anfitrión por el uso de los servicios basándose en un porcentaje de las tarifas de alojamiento o servicio aplicables. Las Tarifas de usuario se mostrarán al usuario cuando se le solicite que confirme o rechace una solicitud de reserva de un Cliente potencial.
    Tarifas de servicio de Migohood: suma de las Tarifas de usuario-cliente y las Tarifas de usuario-anfitrión.
    Tarifas totales: suma de las tarifas de alojamiento o servicio del usuario, y las tarifas de usuario más  impuestos.

    <h4>Reservas y términos financieros de los usuarios y los clientes.</h4>

    Si usted es un usuario y se solicita una reserva para un alojamiento u otro servicio a través de la página web, la aplicación o los servicios, estará obligado a confirmar o rechazar la solicitud de reserva dentro del plazo de solicitud de la reserva. De lo contrario, la solicitud de reserva se cancela automáticamente.
    Cuando se solicita una reserva a través de la página web, la aplicación compartiremos con usted: el nombre propio y apellido del usuario que ha solicitado la reserva, un enlace a la página de perfil de la cuenta de Migohood del usuario-cliente.
    Migohood cobrará las tarifas totales en el momento de la confirmación de la reserva (esto es, cuando el usuario-anfitrión confirme que acepta la solicitud de la reserva) e iniciará el pago de las tarifas de alojamiento y otros servicios (menos las tarifas de usuario-anfitrión de Migohood y cualquier impuestos que corresponda con respecto a las tarifas de usuario-anfitrión como, por ejemplo, el IVA en Colombia o Europa) al usuario-anfitrión en menos de 24 horas desde el momento en que llegue el usuario-cliente al alojamiento o inicie la prestación del servicio correspondiente (excepto en la medida en que se deba una devolución al usuario-cliente). El tiempo que el usuario-anfitrión tardará en recibir los pagos dependerá del método de pago que haya elegido. Algunos de estos métodos implican la participación de terceros procesadores de pagos que pueden imponer al usuario-anfitrión sus propias comisiones adicionales por el uso de sus servicios, incluyendo la deducción de dichas comisiones del importe del pago.
    Si usted adeuda o se compromete a abonar cualquier importe a través de Migohood  (ya sea como consecuencia de sus reservas o sus actos como cliente o de cualquier otra forma), Migohood podrá, pero no estará obligada,  retener el importe adeudado a Migohood de cualquier pago adeudado a usted como usuario, y compensar el importe retenido con la cantidad adeudada por usted a Migohood. Si Migohood procede de la forma indicada anteriormente, la obligación de pago asumida por usted frente a Migohood quedará extinguida en la medida del importe retenido por Migohood, y Migohood ya no tendrá obligación alguna frente a usted, con respecto al importe retenido. Además del importe adeudado, si su cuenta es morosa o tiene derecho a reembolsos en su cuenta, se le podrán cobrar tarifas accesorias además de nuestra recaudación por dichas cantidades morosas o reembolsos. Dichas tarifas o cargos pueden incluir tasas de recaudación, comisiones u otros cargos de terceros. Por el presente, acepta expresamente que toda la comunicación en relación con las cuentas morosas se efectuará por correo electrónico o por teléfono, tal como establece Migohood. Dicha comunicación podrá realizarse por Migohood o por alguien en su nombre, incluido entre otros, un tercero agente de cobros.
    El usuario nombra a Migohood como agente limitado de cobros del usuario al objeto exclusivo de aceptar las tarifas de alojamiento y otros servicios de otros usuarios.
    El usuario acepta considerar los pagos que los clientes realicen a través de Migohood como si se hubieran satisfecho directamente al usuario, por lo que el usuario dispondrá el alojamiento o servicio de los clientes en la forma anteriormente acordada como si el usuario hubiera recibido las tarifas de alojamiento o servicio del usuario. El usuario acepta que Migohood podrá, según la política de cancelación establecida por el usuario permitir que el cliente cancele la reserva y devolver al cliente (a través de Migohood) la parte de las tarifas de alojamiento o servicio especificada en la política de cancelación aplicable.
    Los usuarios entienden que dado que Migohood acepta los pagos de los clientes como agente autorizado limitado de dichos usuarios y que la obligación de Migohood de efectuar los pagos al usuario está sujeta y condicionada a la recepción efectiva de los pagos relacionados de parte de los clientes. Migohood no garantiza los pagos a los usuarios con respecto a aquellas cantidades que no sean efectivamente recibidas de los clientes por Migohood. Al aceptar su designación como agente autorizado limitado del usuario, Migohood no asume responsabilidad alguna por las acciones o las omisiones del usuario.

    <h4>Reservas y términos financieros para los clientes.</h4>
    Los usuarios, no Migohood, son responsables exclusivamente de respetar toda reserva confirmada y poner a la disposición todo alojamiento o servicio reservado a través de la página web, la aplicación y los servicios. Si usted, como cliente, elige firmar una transacción con un usuario para la reserva de un alojamiento u otro servicio, usted acepta y comprende que estará obligado a firmar un acuerdo con el usuario y que usted acuerda aceptar todos los términos, condiciones, reglas y restricciones asociados con dicho alojamiento o servicio impuestos por el usuario.
    Usted acepta y conviene que usted, y no Migohood, será responsable de cumplir las obligaciones de dichos acuerdos, que Migohood no es parte de dichos acuerdos y que, a excepción de las obligaciones de pago que en este acto contrae, Migohood se declara eximida de toda responsabilidad en relación con dichos acuerdos. Usted acepta y conviene que, aunque Migohood no es parte del acuerdo entre usted y el usuario, Migohood actúa como agente de cobros del usuario con el único fin de aceptar en nombre y representación del usuario los pagos que usted realice. Cuando usted paga a Migohood las tarifas totales, se extingue su obligación de pago de las tarifas de alojamiento o servicio para con el usuario, y Migohood es la responsable de transferir al usuario las tarifas de alojamiento o servicio.
    Las tarifas totales que deberán abonarse se mostrarán al cliente antes de que éste envíe su solicitud de reserva. Como se ha apuntado anteriormente, el usuario está obligado a confirmar o rechazar la solicitud de reserva dentro del Plazo de solicitud de la reserva, de lo contrario, la reserva solicitada será cancelada automáticamente. Si se cancela una reserva solicitada (esto es, no la confirma el usuario aplicable), todas las cantidades cobradas por Migohood serán reembolsadas a dicho cliente, en función de las selecciones que haga el cliente a través de la página web y la aplicación, y toda preautorización de la tarjeta de crédito de dicho Cliente será liberada, si es pertinente.
    Usted, como cliente, acepta pagar a Migohood las reservas solicitadas en conexión con su cuenta de Migohood si dichas reservas solicitadas se confirman por parte del usuario pertinente.
    Para establecer una reserva pendiente de la confirmación de su reserva solicitada por parte del usuario pertinente, usted comprende y acuerda que Migohood, en nombre y representación del usuario, se reserva el derecho, bajo su criterio exclusivo, de obtener una preautorización a través de su tarjeta de crédito por las tarifas totales o cargar a su tarjeta de crédito una cantidad nominal, que no supere un dólar (1 USD), o una suma similar en la divisa en la que esté haciendo la transacción (por ejemplo, un euro o una libra esterlina) para verificar su tarjeta de crédito.
    Por norma general, Migohood recaudará las tarifas totales adeudadas una vez que Migohood reciba confirmación de la reserva por parte del usuario pertinente; si fuera necesario, las tarifas totales podrán recaudarse en un momento posterior. Tenga en cuenta que Migohood no puede controlar ninguna tarifa que pueda cobrarse a un cliente por parte de su banco en relación con el cobro de Migohood de las tarifas totales, y Migohood no es ni será responsable de ninguna manera sobre estos cargos por parte del banco.
    En conexión con su reserva solicitada, se le pedirá que dé información de facturación habitual como el nombre, la dirección de facturación e información de tarjeta de crédito bien a Migohood o a su/s procesador/es de pagos de terceros. Usted acuerda pagar a Migohood toda reserva confirmada hecha en conexión con su cuenta de Migohood según estos términos por uno de los métodos descritos en la página web o la aplicación, por ejemplo, por PayPal o tarjeta de crédito. Por el presente usted autoriza el cobro de dichas cantidades cargándolas a la tarjeta de crédito facilitada como parte de la solicitud de la reserva, bien directamente por parte de Migohood o indirectamente a través de un procesador de pagos por Internet de terceros o por uno de los métodos de pago descritos en la página web o la aplicación. Usted también autoriza a Migohood a cargar en su tarjeta de crédito en el caso de daños causados en el alojamiento según se contempla en la sección "Daños a los Alojamientos" y por depósitos de seguridad, si es aplicable. Si se le dirige al procesador o procesadores de pagos de terceros de Migohood, puede que esté sujeto a los términos y las condiciones que rijan el uso del servicio de ese tercero y a las prácticas de recogida de información personal de ese tercero. Revise dichos términos y condiciones y la política de privacidad antes de utilizar los servicios. Una vez que su transacción de reserva confirmada esté completa, usted recibirá un correo electrónico de confirmación que resuma su reserva confirmada.

    <h4>Depósitos de seguridad.</h4>
    Los usuarios pueden elegir incluir depósitos de seguridad como condición para aceptar una reserva para un alojamiento o la prestación de un servicio. Si se incluye como condición un depósito de seguridad de una reserva de un alojamiento o servicio del usuario, y un usuario reclama dicho depósito de seguridad, Migohood, en su condición de agente de cobros del usuario, utilizará esfuerzos comercialmente razonables para cargar el importe del método de pago del cliente en reclama de seguridad, dentro de un periodo de tiempo razonable posterior a la salida del cliente del alojamiento  o  de la terminación de la prestación de un servicio por parte de un usuario. Migohood también utilizará sus esfuerzos razonables comercialmente para responder a las solicitudes y reclamaciones de los usuarios relacionadas con los depósitos de seguridad, pero Migohood no es responsable de administrar o aceptar ninguna reclamación por parte de los usuarios relacionada con los depósitos de seguridad y rechaza todas y cada una de las responsabilidades al  respecto.

    <h4>Tarifas por los servicios de Migohood.</h4>
    En consideración por el uso de la plataforma de Migohood, Migohood cobra las tarifas de servicio. Cuando sea aplicable, se pueden cobrar también impuestos  con respecto a las tarifas de usuario y a las tarifas de cliente. Migohood deduce las tarifas de usuario de las tarifas de alojamiento o servicio del usuario antes de remitir el saldo al usuario conforme a lo descrito en estos términos. Las tarifas de clientes están incluidas en las tarifas totales.
    Migohood transferirá los saldos a los usuarios a través de cheque, PayPal, ingreso directo u otros métodos de pago, tal como se describe en la página web o a través de la aplicación, en la divisa que elija el usuario, en función de las selecciones que realice el usuario a través de la página web, la aplicación y los servicios. Las cantidades se redondearán al alza según la política de aproximación.
    Tenga presente que Migohood podrá imponer o deducir los costes de procesamiento de divisa extranjera con respecto a cualesquiera pagos o desembolsos efectuados por Migohood en monedas distintas del dólar estadounidense. Excepto que se contemple de otro modo en el presente, las tarifas de servicio no son reembolsables.

    <h4>Condiciones financieras y de reservas generales.</h4>
    Si usted, como cliente, cancela su reserva solicitada antes de que la reserva solicitada sea confirmada por el usuario, Migohood cancelará la preautorización de su tarjeta de crédito y/o devolverá las cantidades nominales cargadas a su tarjeta de crédito en relación con la reserva solicitada en un plazo de tiempo comercialmente razonable.
    Si, como cliente, usted desea cancelar una reserva confirmada a través de la página web, la aplicación y los servicios, tanto antes como después de llegar al alojamiento o antes o después de la prestación de un servicio, la política de cancelación del usuario será aplicada a dicha cancelación. Nuestra capacidad de devolver las tarifas de alojamiento y otras cantidades cargadas a su cuenta dependerá de los términos y condiciones de la política de cancelación aplicable. En la página web y en la aplicación hay más información sobre la devolución de cantidades y la política de cancelación. La tarifa de cliente no es reembolsable con independencia de la política de cancelación seleccionada por el usuario.
    Si un usuario cancela una reserva confirmada hecha a través de la página web, los servicios y la aplicación, Migohood reembolsará las tarifas totales de dicha reserva al cliente pertinente dentro de un periodo de tiempo razonable comercialmente de la cancelación y el cliente recibirá un correo electrónico u otra confirmación por parte de Migohood otras alternativas y otra información relacionada. Si un usuario ha cancelado una reserva confirmada y usted, como cliente, no ha recibido ningún correo electrónico u otra comunicación de Migohood, póngase en contacto con Migohood.
    Si, como usuario, usted cancela una reserva confirmada, usted acepta que Migohood podrá aplicarle sanciones o tomar medidas, incluyendo publicar automáticamente una valoración indicando que se canceló una reserva, mantener su calendario  no disponible o bloqueado durante las fechas de la reserva cancelada, o imponer una comisión de cancelación (que se retendrá de sus futuros pagos o le será cargado en la tarjeta de crédito registrada en su cuenta de Migohood). Antes de que decida cancelar una reserva se le informará de las situaciones en las que se aplica una comisión de cancelación.
    En determinadas circunstancias, Migohood podrá decidir, a su elección exclusiva, que es necesario o conveniente cancelar una reserva confirmada hecha a través de la página web, la aplicación o los servicios. Esta decisión puede obedecer a los motivos especificados en la política de causas de fuerza mayor de Migohood o a otros motivos. Asimismo, Migohood podrá, a su elección exclusiva, determinar el reembolso a favor del cliente de la totalidad o de parte de las cantidades cobradas a dicho cliente de conformidad con la política de reembolso a clientes. Usted acepta que Migohood y el cliente o el usuario en cuestión no serán responsables en modo alguno por tales cancelaciones o reembolsos.
    Si, siendo usted usuario, su cliente cancela una reserva ya confirmada o Migohood decide que es necesario cancelar una reserva ya confirmada, y Migohood realiza el reembolso al cliente  de  acuerdo a la política de reembolsos usted acepta que, en el caso de que ya haya pagado Migohood, Migohood tendrá derecho a recuperar el importe del reembolso que realizó al cliente, mediante la sustracción de dicho importe de cualquier futura tarifa de alojamiento que se le deba.

    <h4>Pagos recurrentes.</h4>
    En algunos casos, los clientes pueden estar obligados a hacer pagos recurrentes e incrementales para las tarifas totales que se deban por una reserva confirmada antes del comienzo de su estancia en el alojamiento pertinente o de la prestación de un servicio determinado Se pondrá a la disposición pública más información sobre pagos recurrentes a través de la página web, la aplicación y los servicios, si es aplicable. Si se aplican pagos recurrentes a una reserva confirmada, el cliente autoriza a Migohood, en nombre y representación del usuario, a cobrar las tarifas totales y el usuario acepta que dicha entidad realice los pagos al usuario en las cantidades y con la frecuencia asociada con los pagos recurrentes aplicables, cada uno identificado en la Página web, la aplicación y los servicios.

    <h4>Aproximación.</h4>
    Migohood podrá, a su elección exclusiva, redondear al alza o a la baja las cantidades pagaderas a/por los clientes o usuarios a la cifra entera funcional más aproximada en la que se exprese la divisa correspondiente (por ejemplo, a la cifra de dólares, euros u otras divisas soportadas); por ejemplo, Migohood redondeará la cantidad de $101,50 a $102,00, y de $101,49 a $101.00.
    Algunas divisas se expresan con cifras muy elevadas. En estos casos, Migohood podrá determinar que la unidad base funcional en la que dichas divisas se denominen será 10, 100 o 1.000. Los ejemplos correspondientes relativos a tales divisas serían para Migohood el de una cantidad de 1.045 a 1.050 y de 1.044 a 1.040, o de 35.450 a 35.500 y de 35.449 a 35.400, o de 837.500 a 838.000 y de 837.499 a 837.000.

    <h4>Errores en la tramitación de pagos.</h4>
    Tomaremos medidas para subsanar cualquier error en la tramitación de pagos del que tengamos conocimiento. Dichas medidas podrán incluir la realización de un abono o un adeudo (según el caso) con el mismo medio de pago utilizado para el pago original a favor o por parte de usted, de modo que usted acabe recibiendo o abonando el importe correcto.

    <h4>Donaciones.</h4>
    Los usuarios pueden hacer una donación de la porción de los fondos que reciben de reservas confirmadas hechas a través de la página web, la aplicación y los servicios a la Fundación de Migohood. Nosotros no aceptaremos ninguna responsabilidad ni obligación al respecto, si el usuario de hecho hace la donación que ha prometido hacer. En estos casos, el usuario en cuestión será el responsable de cumplir con las leyes y normativas que resulten de aplicación a tales donaciones y/o actividades de recaudación de fondos.

    <h4>Impuestos.</h4>
    La normativa fiscal puede obligarnos a solicitar los correspondientes datos fiscales a nuestros usuarios o a practicar las retenciones fiscales preceptivas sobre las cantidades satisfechas a los usuarios, o a adoptar ambas medidas. Así por ejemplo, la normativa de la agencia tributaria estadounidense (IRS) estipula que estamos obligados a solicitar el formulario W-9 del IRS a nuestros usuarios residentes en Estados Unidos y el correspondiente formulario W-8 (es decir, el formulario W-8BEN) del I.R.S. a los usuarios no residentes en Estados Unidos que ofrezcan alojamiento en Estados Unidos. Usted, como usuario, es el único responsable de mantener la información de sus declaraciones tributarias, actualizada, completa y correcta. Si usted, como usuario, no nos facilita la documentación que consideremos necesaria para poder cumplir con nuestra obligación (en su caso) de retención de impuestos de los pagos (por ejemplo, cuando usted sea un usuario residente en Estados Unidos y no nos facilite el formulario W-9 del IRS cumplimentado), nos reservamos el derecho a nuestra discreción de retener todos los pagos que debamos efectuar a su favor hasta que se resuelva el asunto, a practicar las retenciones que establezca la ley, o a adoptar ambas medidas.
    Usted, como usuario, entiende y acepta que usted es responsable exclusivamente de la determinación de  sus requisitos de informe de los impuestos aplicables, y  los impuestos que deben incluirse e incluir los impuestos que deban cobrarse u obligaciones relacionadas con los impuestos aplicables. Asimismo, usted es el responsable de remitir a las autoridades competentes todos los impuestos incluidos o recibidos por usted. Migohood no puede y no ofrece consejo relacionado con impuestos a ningún usuario.
    Cuando sea aplicable, o a petición de un usuario, Migohood podrá emitir una factura válida de IVA a dicho usuario.
    Usted reconoce y acepta que las administraciones, los departamentos o las autoridades competentes país en el que esté situado su alojamiento podrán exigir que se practiquen a los clientes o a los usuarios las retenciones fiscales aplicables sobre las cantidades satisfechas por el derecho a utilizar y/u ocupar el alojamiento y se ingresen las cantidades retenidas ante las autoridades fiscales competentes. Aunque las leyes de las diferentes jurisdicciones pueden variar, podrá exigirse que las referidas cantidades sean retenidas e ingresadas como un porcentaje de la renta o las Tarifas de alojamiento fijadas por los usuarios, como un importe fijo por día u otras modalidades. Estas cantidades en ocasiones se denominan "impuestos de ocupación", "impuestos hoteleros", "impuestos de alojamiento", "impuestos transitorios", "impuestos sobre las ventas o la utilización", "impuestos sobre el valor añadido", "impuestos de habitación" o "impuestos turísticos" (en adelante, los "impuestos de ocupación").

    <h4>Recaudación y Declaración del Impuesto de Ocupación.</h4>
    En determinadas jurisdicciones, Migohood podrá optar, a su exclusivo criterio, por facilitar la recaudación y declaración de los impuestos de ocupación por cuenta de los clientes o de los usuarios, de acuerdo con las instrucciones del presente contrato de términos y uso de condiciones siempre y cuando en la jurisdicción fiscal en cuestión Migohood o los usuarios tengan la obligación de recaudar y declarar las cantidades mencionadas. En cualquier jurisdicción en la que decidamos recaudar y declarar impuestos directamente, sea usted cliente o usuario, acepta por el presente a que en lugar de que el usuario recaude los impuestos de ocupación de los clientes y los declare a la autoridad fiscal, sea Migohood quien recaude dichos impuestos de ocupación a los clientes por cuenta de los usuarios en el momento en que se cobren las tarifas de alojamiento o servicio del usuario, y declare tales impuestos de ocupación ante las autoridades fiscales. Cuando Migohood recaude y declare los impuestos de ocupación en una jurisdicción por primera vez, Migohood notificará dicha circunstancia a aquellos usuarios que en ese momento tengan publicadas ofertas de alojamiento en dichas jurisdicciones.
    Tanto clientes como usuarios podrán visualizar por separado en los documentos de la transacción la cantidad, en su caso, de impuestos de ocupación recaudados y declarados por Migohood. Cuando Migohood realice directamente la recaudación y la declaración, los clientes y los usuarios aceptan que los usuarios no puedan intentar recaudar o recaudar impuesto de ocupación alguno relacionado con sus alojamientos en Migohood en dicha jurisdicción.
    Usted acuerda expresamente eximir, defender, indemnizar y mantener a Migohood, sus filiales y subsidiarias, sus consejeros, directores, empleados y agentes indemnes de cualesquiera reclamaciones, responsabilidades, daños, pérdidas, deudas, obligaciones y gastos, incluidos entre otros, los honorarios razonables de abogados o contables, que se deriven de o estén relacionados de alguna manera con los impuestos de ocupación, incluidos entre otros, su aplicabilidad, el cálculo, la recaudación o declaración de impuestos de ocupación de cualquier cantidad o del total en relación con sus transacciones o con los alojamientos o los servicios.
    En cada jurisdicción en la que recaudemos y declaremos impuestos, los usuarios y los clientes otorgan su autorización expresa, sin más aviso, para que almacenemos, llevemos a cabo la transferencia y divulguemos a la autoridad fiscal los datos y demás información relativa a ellos o a sus transacciones, reservas, alojamientos o impuestos de ocupación, prestación de servicios, incluidos entre otros, la información de identificación personal, como el nombre del usuario o del cliente, las direcciones de los alojamientos, las fechas e importes de las transacciones, los números de identificación fiscal, el importe de los impuestos recaudados de los clientes o supuestamente devengados, la información de contacto o similar.

    <h4>Opción de Declaración de Impuestos por el usuario.</h4>
    En otras jurisdicciones, Migohood puede decidir, a su propia discreción, recaudar el impuesto de ocupación en nombre de los usuarios y clientes de acuerdo con las instrucciones del usuarios de incluir en el proceso de reserva una partida específica relativa al impuesto de ocupación, mediante la que el usuario ordene que los impuestos de ocupación de los Clientes se remitan directamente al usuario para que éste declare dichos impuestos directamente a la autoridad fiscal competente. En cualquier jurisdicción en la que decidamos recaudar mediante la Opción de Declaración de Impuestos por el usuario, tanto si usted es un cliente como un usuario, por el presente ordena y autoriza a Migohood a remitir al usuario los impuestos de ocupación recibidos de los Clientes en el momento de recepción de los honorarios de alojamiento o servicio del usuario, quien está obligado a declarar dichos impuestos directamente a la Autoridad Fiscal competente. Si Migohood ofrece la Opción de Declaración de Impuestos por el usuario y un usuario opta por ella en cualquier jurisdicción, los usuarios y clientes serán los únicos responsables del pago y envío de todos y cualesquiera impuestos que puedan aplicarse a los alojamientos o servicios del usuario.
     Usted acepta y entiende que Migohood no es responsable, y que no declarará ningún impuesto de ocupación a la autoridad fiscal en el supuesto de haber optado por la Opción de Declaración de Impuestos por el usuario.
    Por el presente, usted acepta que mediante terceros procesadores de pago, Migohood está meramente procesando su elección de enviarle directamente los impuestos de ocupación de los clientes para que usted los declare a la Autoridad Fiscal. Usted acuerda expresamente eximir, defender e indemnizar a Migohood, sus filiales y subsidiarias, así como a sus consejeros, directores, empleados y agentes, de cualesquiera reclamaciones, responsabilidades y/o daños, pérdidas, deudas, obligaciones y gastos, incluyendo pero no limitado a los honorarios razonables de abogados o de contables, que se deriven de o estén de algún modo relacionados con los impuestos de ocupación otros, incluido sin carácter limitativo, la aplicación, el cálculo y la recaudación de alguna parte o del total de los impuestos de ocupación por sus operaciones o alojamientos. En cualquier jurisdicción en la que facilitemos la Opción de Declaración de Impuestos por el usuario, los usuarios y los clientes nos autorizan expresamente, sin más aviso, para almacenar, transferir y divulgar a la autoridad fiscal competente sus datos y otra información, así como sus operaciones, reservas, alojamientos e impuestos de ocupación u otros, incluyendo a la información de identificación personal como el nombre del usuario o el cliente, las direcciones de los anuncios, las fechas y los importes de las operaciones, los números de identificación fiscal, el importe de los impuestos recibidos o supuestamente devengados por los usuarios de los clientes, los datos de contacto e información similar.

    <h4>Disposiciones varias sobre el impuesto de ocupación.</h4>
    Tanto si es un cliente como si es un usuario, usted acepta que ninguna demanda ni ningún hecho que dé lugar a una reclamación relacionada con la Opción de Declaración de Impuestos por el usuario o la Recaudación y Declaración de impuestos será extensiva a ningún proveedor o distribuidor que Migohood pueda utilizar en relación con estas funciones, en su caso. Los huéspedes, clientes y los usuarios aceptan que podremos reclamarle el pago de cantidades adicionales en el supuesto de que los impuestos retenidos y/o ingresados sean insuficientes para que usted cumpla íntegramente con sus obligaciones frente a las autoridades fiscales, y acuerdan que la única acción que usted podrá ejercitar con respecto a los impuestos de ocupación retenidos consistirá en obtener la devolución, por parte de las autoridades fiscales competentes, de los impuestos de ocupación retenidos por Migohood de conformidad con los procedimientos aplicables que establezcan dichas autoridades fiscales.
    En las jurisdicciones en las que no hayamos optado por la Recaudación y Declaración de los impuestos de ocupación, la Opción de Declaración de Impuestos por el usuario o cualquier otro medio o método que sea de aplicación en su jurisdicción, los usuario y los clientes serán los únicos responsables de la recaudación y/o declaración de cualquiera y todos los impuestos de ocupación que fueran aplicables a los alojamientos.
    Los usuarios y clientes reconocen y aceptan que en algunas jurisdicciones Migohood podrá decidir no optar por la Recaudación y Declaración de los impuestos de ocupación o no tendrá capacidad para recaudar y declarar los impuestos de ocupación. Ninguna disposición de este acuerdo es una declaración o garantía de que Migohood recaudará y/o declarará el impuesto de ocupación en cualquier lugar, incluidas jurisdicciones específicas, o de que Migohood continuará recaudando o declarando el impuesto de ocupación. Migohood se reserva el derecho, a su propia discreción, de cesar en la recaudación y declaración del impuesto de ocupación (independientemente del método empleado o que se emplee en el futuro) por cualquier motivo o sin motivo, siempre que lo notifique de manera razonable a los usuarios en cualquier jurisdicción en la que Migohood decida cesar en la Recaudación y Declaración de Impuestos.

    <h4>Daños a los alojamientos.</h4>
    Como cliente, usted es responsable de dejar el alojamiento en la condición en la que estaba cuando llegó. Usted acepta y conviene que, como cliente, usted es responsable de sus propios actos y omisiones y también es responsable de los actos y omisiones de cualquier persona a la que invite, o a la que de cualquier otra manera ofrezca acceso, al alojamiento. En el caso de que un usuario afirme lo contrario y dé evidencia de daños, incluyendo entre otros, fotografías, usted acepta pagar el coste de la sustitución de los artículos dañados por artículos equivalentes. Después de ser notificado de la reclamación y se le den cuarenta y ocho (48) horas para responder, el pago será cargado y cobrado a la tarjeta de crédito que tengamos en su cuenta de Migohood. Migohood también se reserva el derecho a cargar en la tarjeta de crédito que tengamos en su cuenta de Migohood, o cobrarle de cualquier otra manera el pago y utilizar cualquier vía disponible para Migohood en este respecto, incluyendo el uso de depósitos de seguridad, en situaciones en las que, bajo el criterio exclusivo de Migohood, se haya determinado que usted ha dañado cualquier alojamiento, incluyendo entre otros, en relación con cualquier solicitud de pago hecha por los usuarios, y en relación con cualquier pago hecho por parte de Migohood a los usuarios. Si no podemos cargar la tarjeta de crédito que tengamos o de otra manera cobrarle el pago, usted acuerda remitir el pago de cualquier daño al alojamiento al usuario pertinente o a Migohood.
    Tanto los clientes como los usuarios acuerdan cooperar con y asistir a Migohood de buena fe, y ofrecer a Migohood dicha información y tomar dichas medidas que sean solicitadas razonablemente por parte de Migohood, en conexión con cualquier reclamación o queja hecha por usuarios relacionados con los alojamientos o cualquier propiedad personal u otra situada en un alojamiento o con respecto a cualquier investigación realizada por Migohood o un representante de Migohood con respecto al uso o abuso de la página web, la aplicación o los servicios. Si usted es cliente, tras la solicitud razonable por parte de Migohood, y en tanto usted pueda razonablemente hacerlo, usted acuerda participar en mediación o proceso de resolución similar con un usuario.
    Si usted es un cliente, acepta y comprende que Migohood podrá presentar una reclamación en virtud de su seguro de vivienda, de inquilino o de otra póliza de seguro relacionada con cualquier daño o pérdida que pueda haber causado de la que sea responsable con respecto a un alojamiento o cualquier propiedad personal u otra situada en un alojamiento. Usted acepta cooperar con y ayudar a Migohood de buena fe, y facilitar a Migohood dicha información según se solicite razonablemente por parte de  para hacer una reclamación en virtud de su seguro de vivienda, de inquilino o de otra póliza de seguros, incluyendo, entre otros, firmar documentos y emprender actos ulteriores que Migohood pueda solicitar razonablemente para ayudar a Migohood a lograr lo anterior.

    <h4>Prolongar la estancia sin el consentimiento del usuario.</h4>
    Los clientes aceptan que una reserva confirmada es meramente una licencia otorgada por el usuario al Cliente para usar un alojamiento durante el periodo limitado de la reserva confirmada y conforme al acuerdo entre el cliente y el usuario. Asimismo, los clientes aceptan abandonar el alojamiento no más tarde de la hora de salida que el usuario especifique en el alojamiento o la hora que el usuario y el cliente acuerden. Si un cliente permanece más tiempo de la hora de salida acordada sin el consentimiento del alojamiento, el cliente ya no podrá permanecer en el alojamiento y el usuario tendrá derecho a expulsar al cliente. Además, los clientes aceptan que el usuario podrá cargarles, por cada 24 horas en las que los clientes permanezcan más tiempo del periodo acordado sin el consentimiento del usuario, una tarifa nocturna adicional de dos veces la tarifa media nocturna de alojamiento inicialmente abonada por el cliente. Dicha tarifa estará destinada a cubrir los inconvenientes sufridos por el usuario, más todas las tarifas del servicio aplicables, los impuestos y cualquier gasto legal contraído por el usuario para expulsar al cliente. Los clientes aceptan que Migohood, en calidad de agente recaudador del usuario, cargue dichas sumas adicionales al cliente mediante la tarjeta de crédito u otro método de pago registrado. Adicionalmente, Migohood podrá recuperar cualesquiera costes y gastos en que hubiera incurrido al recaudar las sumas adicionales mediante el cargo en la tarjeta de crédito del cliente u otro método de pago registrado.

    <h4>Divisa extranjera.</h4>
    La plataforma de Migohood facilita las reservas entre clientes y usuarios que prefieran pagar y recibir los pagos en distintas divisas, lo que podrá exigir que las conversiones de divisas se ajusten a las diferentes preferencias de divisa. Pese a que la plataforma de Migohood permite a los usuarios ver el precio de los alojamientos y servicios en varias divisas, las divisas disponibles para los usuarios que realicen y reciban pagos podrán ser limitadas, y podrían no incluir la divisa por defecto de una zona geográfica en concreto.
    Cada conversión de divisa extrajera se tramita a un tipo de conversión de divisa extranjera. En general, este tipo se refiere a la cantidad de una divisa que debe abonarse para comprar una determinada cantidad de otra divisa en un momento dado. Por ejemplo, si cuesta US$125,00 comprar  €100,00, el tipo de conversión de divisa de dólares estadounidenses a Euros sería 1,25, y el tipo de conversión de divisa de Euros a dólares estadounidenses sería 0,8. Los tipos conversión de divisa variarán en cada momento.

    <h4>Definiciones clave.</h4>
    "Divisa de Visualización" significa la divisa en la que los usuarios ven los precios del alojamiento o servicio en la plataforma de Migohood. Los clientes pueden elegir y cambiar la divisa de visualización para poder ver los precios de un alojamiento o servicio del usuario en las diferentes divisas soportadas.
    "Divisa de Reserva" significa la divisa en la que un cliente debe efectuar el pago de su reserva. En el momento en el que el cliente remita la solicitud de reserva, la plataforma de Migohood seleccionará la divisa de reserva, dependiendo del país de origen del cliente y de los métodos de pago disponibles para ese país. Migohood únicamente soporta determinadas divisas como divisas de reserva. La divisa de reserva podrá ser distinta a la divisa del alojamiento o servicio del usuario correspondiente.
    "Divisa del Listado" significa la divisa en la que se establecen los precios del alojamiento o servicio. La divisa del alojamiento o servicio es fijada por el usuario.
    "Divisa de Pago" significa la divisa en la que se abonará un pago al usuario. La divisa de pago es fijada por el usuario.
    "Tipo de Cambio Base" significa el tipo aplicado por Migohood en todo el sistema para la conversión de divisa extranjera y que está vigente en el momento en que se tramita la correspondiente conversión de divisa extranjera, sin incluir ninguna tarifa o recargo cobrado por Migohood. Migohood establece el tipo de cambio base utilizando la información de uno o varios terceros.
    "Tipo de Cambio Ajustado" significa el tipo de cambio que se aplica a la conversión de divisa extranjera y que se calcula añadiendo un recargo al tipo de cambio base. Este recargo representa el margen impuesto por Migohood en concepto de gastos de mantenimiento y riesgos de tipo de cambio.

    <h4>Conversiones de divisas en la plataforma de Migohood.</h4>
    Migohood tramitará una conversión de divisa extranjera en las siguientes situaciones:

    La divisa de visualización es distinta de la divisa del alojamiento o servicio  del usuario cuando el cliente ve un alojamiento o servicio del usuario: Migohood calculará las tarifas totales estimadas en la divisa de visualización, aplicando bien el tipo de cambio base o el tipo de cambio ajustado en el momento de visualizar las tarifas totales estimadas en la divisa del alojamiento o servicio del usuario. El tipo de cambio ajustado se aplicará si la divisa de visualización es una divisa de reserva soportada, y es distinta de la divisa del alojamiento o servicio del usuario. En caso contrario, se aplicará el tipo de cambio base.
    La divisa de reserva es distinta de la divisa del alojamiento  o servicio del usuario cuando el cliente remite una solicitud de reserva con respecto a un alojamiento o servicio del usuario: Migohood calculará las tarifas totales en la divisa de reserva, aplicando bien el tipo de cambio base o el tipo de cambio ajustado en el momento de efectuarse la solicitud de reserva a las tarifas totales en la divisa del alojamiento o servicio. El cliente podrá ver el tipo de cambio real que se ha aplicado. Las tarifas de cliente, que son un porcentaje de las correspondientes tarifas de alojamiento, se calcularán tomando como base las tarifas de alojamiento en la divisa de reserva (es decir, después de realizarse la conversión de la divisa del alojamiento o servicio. El tipo de cambio ajustado se aplicará si la divisa de visualización es la misma que la divisa de reserva, y es distinta de la divisa del alojamiento o servicio. En caso contrario, se aplicará el tipo de cambio base.
    La divisa de pago es distinta de la divisa del Migohood cuando Migohood inicia un pago: por norma general, Migohood calculará el pago que deberá abonarse al usuario, aplicando el tipo de cambio base en la fecha en la que Migohood inicie el pago de las tarifas de alojamiento y servicios (menos las tarifas de usuario de Migohood y cualquiera impuestos correspondientes a las tarifas de usuario como, por ejemplo, el IVA en Europa o Colombia) en la divisa del Migohood. En aquellos casos en los que el método de pago seleccionado por el usuario implique la participación de algún tercer procesador de pagos (como, por ejemplo, Western Union), Migohood enviará el importe del pago al procesador en una divisa principal (por ejemplo, dólares estadounidenses), aplicando el tipo de cambio base correspondiente a la divisa del alojamiento o usuario a esa divisa principal, el usuario podrá ver el importe del pago enviado por Migohood en esa divisa principal en su historial de operaciones de la página web o la aplicación, y el procesador calculará el pago real que corresponde al usuario aplicando su propio tipo de conversión de divisa extranjera correspondiente a esa divisa principal con respecto a la divisa de pago.
    Cuando una reserva confirmada sea modificada o cancelada, y se haya realizado una conversión de divisa extranjera en el momento de remitir la reserva: la conversión de divisa extranjera para cualesquiera pagos adicionales exigidos al cliente o cualquier reembolso a éste se tramitará utilizando el mismo tipo que el aplicado para el pago anterior del cliente.
    Cuando usted, como cliente, remita una solicitud de reserva de un alojamiento o servicio, podrá ver el tipo de cambio real utilizado para calcular las tarifas totales en la divisa de reserva. Cuando se aplique el tipo de cambio ajustado, usted poder ver el recargo incluido en el tipo. El tipo de cambio real (y cualquier recargo incluido en el mismo) también quedará indicado en el recibo de facturación de su reserva.
    Migohood actualiza regularmente el tipo de cambio base, si bien no lo hace en tiempo real. En particular, Migohood no siempre modifica el tipo de cambio base inmediatamente cuando sus gastos de tipo de cambio experimentan una variación. En consecuencia, el tipo de cambio base puede no ser idéntico al tipo de mercado aplicable y vigente en el momento concreto en que se tramita la conversión de divisa extranjera.
    Tenga en cuenta que la compañía que tramite sus pagos (por ejemplo, la compañía emisora de su tarjeta bancaria o de crédito) utilizará un tipo de conversión y podrá imponer una comisión por ello, si su cuenta bancaria o tarjeta se denomina en una divisa distinta a la divisa de reserva o a la divisa de pago, respectivamente. De igual modo, los terceros procesadores de pagos también podrán utilizar un tipo de conversión o imponer una comisión por conversión sobre los pagos que realice. Estas comisiones y tarifas por conversión de divisa no son conocidas o controladas por Migohood.

    <h4>Privacidad.</h4>
    Usted acepta que la Política de privacidad de Migohood (según se modifique en cada momento) regula la recogida y uso por parte de Migohood de su información personal.

    <h4>Propiedad.</h4>
    La página web, la aplicación, los servicios y los contenidos colectivos están protegidos por derechos de autor, marcas comerciales y otras leyes de los Estados Unidos y otros países extranjeros. Usted acepta y conviene que la página web, la aplicación y los servicios y los contenidos colectivos, incluyendo todos los derechos de propiedad intelectual asociados, son propiedad exclusiva de Migohood y sus licenciantes. Usted no retirará, alterará ni ocultará ningún aviso de derechos de autor, marca comercial, marca de servicio u otro derecho propietario incorporado a, o que acompañe a la página web, la aplicación, los servicios o los contenidos colectivos

    <h4>Condiciones adicionales.</h4>
    Nuestros servicios disponen de diferentes productos y ofertas; por lo que, a veces, se aplicarán condiciones adicionales o requisitos de productos para utilizar estos productos. Por ejemplo, se aplican condiciones adicionales si efectúa una recomendación de Migohood a nuevos usuarios. Si las condiciones adicionales están disponibles para el producto o servicios pertinentes que usted utiliza, esas condiciones adicionales pasan a formar parte de las presentes condiciones.

    <h4>Términos específicos sobre créditos de alojamiento o servicios.</h4>
    Los créditos de alojamiento o servicios sólo pueden ser canjeados para reservas confirmadas a través de la página web, la aplicación y los servicios, y después de que usted acumule créditos de alojamiento o servicios, dichos créditos de alojamiento o servicios se aplicarán automáticamente a su siguiente reserva confirmada hecha a través de la página web, la aplicación y los servicios. Los créditos de alojamiento o servicios son únicamente créditos y no tienen ningún valor monetario ni pueden devolverse o canjearse por dinero en efectivo. Usted sólo puede canjear créditos de alojamiento o servicios después de que estos se vean reflejados en su cuenta de Migohood. El ámbito, la variedad y el tipo de servicios y productos que pueda obtener al canjear créditos de alojamiento o servicios pueden cambiar en cualquier momento.
    Los créditos de alojamiento o servicios caducan tres (4) años desde la fecha que se acumularan los últimos créditos de alojamiento y servicios en su cuenta de Migohood. Migohood le notificará a la dirección de correo electrónico que facilitará durante su registro de cuenta en treinta (30) días de cuando estén programados caducar los créditos alojamiento y servicios de su cuenta. Si por algún motivo usted cree que hay alguna discrepancia sobre su saldo de créditos de alojamiento y servicios, póngase en contacto con nosotros. Migohood puede obligarle a presentar información adicional para tomar una determinación sobre su saldo. Todas las decisiones sobre su saldo serán finales y bajo criterio exclusivo de Migohood. Usted es responsable de cualquier consecuencia fiscal que pueda resultar del canje o uso de los créditos de alojamiento y servicios. Cuando sea aplicable, Migohood puede estar obligada a contabilizar el I.V.A en algunos servicios para los que se canjean créditos de alojamiento y servicios.
    Sin limitación de ninguna de las disposiciones de los presentes términos, y con sujeción a la ley aplicable, todos los créditos de alojamiento y servicios expiraran si su cuenta de Migohood se rescinde o suspende por cualquier motivo bajo el criterio exclusivo de Migohood, o si Migohood interrumpe la provisión de la página web, la aplicación, los servicios.

    <h4>Licencia de la Aplicación.</h4>
    Con sujeción al cumplimiento de estos términos, Migohood le concede una licencia limitada no exclusiva y no transferible para descargar e instalar una copia de la aplicación en cada dispositivo móvil u ordenador que sea de su propiedad o controle y ejecutar dicha copia de la aplicación exclusivamente para su propio uso personal. Además, con respecto a cualquier aplicación con origen en la App Store), usted solamente utilizará la aplicación con origen en la App Store en un producto de marca Apple que ejecute iOS (sistema operativo propiedad de Apple) y según permitan las reglas de uso establecidas en los términos de servicio de la App Store de Apple. Migohood se reserva todos los derechos de la aplicación no concedidos de manera expresa a usted por estos términos.

    <h4>Acceso y descarga de la aplicación desde iTunes.</h4>
    Lo siguiente se aplica a cualquier aplicación a la que se acceda o se descargue desde la App Store de Apple:
     Usted acepta y conviene que estos términos están concluidos por usted y Migohood solamente, y no Apple. Migohood  no Apple, es responsable exclusivamente de la aplicación con origen en la App Store y su contenido. Su uso de la aplicación con origen en la App Store tiene que cumplir con los términos de servicio de la App Store.
    Usted acepta que Apple no tiene obligación en absoluto de ofrecerle servicios de mantenimiento y asistencia con respecto a la aplicación con origen en la App Store.
    En el caso de que de la aplicación con origen en la App Store incumpla cualquier garantía aplicable, usted puede notificarlo a Apple, y Apple reembolsará el precio de compra de la aplicación con origen en la App Store a usted y en todo lo que permita la ley aplicable, Apple no tendrá ninguna otra obligación de garantía en absoluto con respecto a la aplicación con origen en la App Store. Igual que entre Migohood y Apple, todas las otras reclamaciones, pérdidas, responsabilidades, daños, costes o gastos atribuibles a cualquier incumplimiento de cualquier garantía serán responsabilidad exclusiva de Migohood.
    Usted y Migohood aceptan que, igual que entre Migohood y Apple, Apple no es responsable de resolver ninguna reclamación que usted tenga o ninguna reclamación de ningún tercero relacionada con la aplicación con origen en la App Store o su posesión y uso de la aplicación con origen en la App Store incluyendo, entre otros: reclamaciones de responsabilidad de producto; toda reclamación de que la aplicación con origen en la App Store no cumple algún requisito legal o normativo aplicable; y reclamaciones que surjan de protección de consumidores o legislación similar.
    Usted y Migohood aceptan que, en el caso de una reclamación de tercero de que la aplicación con origen en la App Store, o su posesión y uso de esa aplicación con origen en la App Store, infringe esos derechos de propiedad intelectual del tercero, igual que entre Migohood y Apple, Migohood, no Apple, será responsable exclusivamente de la investigación, defensa, liquidación y descarga de cualquier reclamación de infracción de propiedad intelectual según lo requieran estos términos.
    Usted y Migohood aceptan y convienen que Apple, y las subsidiarias de Apple, son beneficiarias terceras de estos términos según se relaciona con su licencia de la aplicación con origen en la App Store, y que después de su aceptación de los términos y las condiciones de estos términos, Apple tendrá derecho (y se considerará que ha aceptado el derecho) de aplicar estos Términos en relación con su licencia de la aplicación con origen en la App Store contra usted como beneficiario tercero del mismo.
    Sin limitación de ningún otro término de estos términos, usted tiene que cumplir con todos los términos de terceros aplicables del acuerdo cuando utilice la aplicación con origen en la App Store.

    <h4>Contenidos de Migohood y licencia de los contenidos de los miembros.</h4>
    Sujeto al cumplimiento de los términos y condiciones de estos términos, Migohood le concede una licencia limitada no exclusiva y no transferible para acceder y visualizar cualquier contenido de Migohood exclusivamente para sus propósitos personales y no comerciales y acceder y visualizar cualquier contenido de miembro al que se le permita acceso, exclusivamente para sus propósitos personales y no comerciales. Usted no tiene derecho a sublicenciar los derechos de licencia concedidos en esta sección.
    Usted no utilizará, copiará, adaptará, modificará, preparará trabajos derivados, distribuirá, licenciará, venderá, transferirá, exhibirá públicamente, ejecutará públicamente, transmitirá, emitirá ni de ninguna otra manera explotará la página web, la aplicación, los servicios ni los contenidos colectivos, excepto según se permita expresamente en estos términos. No se le concede ninguna licencia o derecho a usted por implicación ni de ninguna otra manera bajo los derechos de propiedad intelectual que sean propiedad de Migohood o sus licenciantes, o que estén bajo su control, excepto las licencias y derechos concedidos expresamente en estos términos.

    <h4>Contenido de los miembros.</h4>
    Nosotros podemos, bajo nuestro criterio exclusivo, permitirle a usted publicar, cargar, colgar, presentar o transmitir contenidos de miembros. Al hacer disponible cualquier contenido de miembros en o a través de la página web, la aplicación y los servicios, usted por el presente concede a Migohood una licencia mundial, irrevocable, perpetua (o por el plazo de protección), no exclusiva, transferible, libre de royalties, con derecho a sublicenciar, utilizar, visualizar, copiar, adaptar, modificar, distribuir, licenciar, vender, transferir, exhibir públicamente, ejecutar públicamente, transmitir, descargar de manera continuada, emitir, acceder, visualizar y de cualquier otra manera explotar dicho contenido de miembro en, a través de o gracias a la página web, la aplicación y los servicios o para promoverlos o comercializarlos. Migohood no reclama ningún derecho de propiedad sobre dicho contenido de miembro y nada de estos términos se considerará que restringe dichos derechos que usted pueda tener para utilizar y explotar dicho contenido de miembro.
    Usted acepta y conviene que usted es responsable exclusivamente de todo el contenido de miembro que ponga a disposición a través de la página web, la aplicación y los servicios. Consecuentemente, usted declara y garantiza que: Usted es el propietario exclusivo y único de todo el contenido de miembro que ponga a disposición a través de la página web, la aplicación y los servicios o usted tiene todos los derechos, licencias, consentimientos y liberaciones que son necesarios para conceder a Migohood los derechos de dicho contenido de miembro, según se contempla bajo estos términos; y ni el contenido de miembro ni su publicación, carga, cuelgue, envío o transmisión del contenido de miembro o el uso por parte de Migohood del contenido del miembro en, a través de, o gracias a la página web, la aplicación y los servicios infringirá, se apropiará o violará la patente, derecho de autor, marca comercial, secreto comercial o derechos morales de terceros u otros derechos propietarios o de propiedad intelectual, o derechos de publicidad o privacidad, o tendrán como resultado la violación de cualquier ley o regulación aplicable.

    <h4>Enlaces.</h4>
    La página web, la aplicación y los servicios pueden contener enlaces a páginas web o recursos de terceros. Usted acepta y conviene que Migohood no es responsable ni está sujeta a: la disponibilidad o exactitud de dichas páginas web o recursos; o los contenidos, productos o servicios que se encuentren o estén disponibles en dichas páginas web o recursos. Los enlaces a dichas páginas web o recursos no implican ningún endoso por parte de Migohood a dichas páginas web o recursos a los contenidos, productos o servicios disponibles desde dichas páginas web o recursos.  Usted acepta la responsabilidad exclusiva y asume todos los riesgos que surjan de su uso de dichas páginas web o recursos o de los contenidos, productos o servicios que se encuentren o estén disponibles en dichas páginas web o recursos.
    Algunas partes de la plataforma de Migohood funcionan con los servicios de localización geográfica Google Maps o Google Earth, incluyendo las interfaces de programación de aplicaciones (API) de Google Maps. El uso que usted haga de Google Maps o Google Earth estará sujeto a las condiciones de uso de Google.

    <h4>Avisos sobre derechos propietarios.</h4>

    Todas las marcas comerciales, marcas de servicio, logotipos, nombres comerciales y cualquier otra designación propietaria de Migohood utilizados en el presente son marcas registradas o marcas comerciales de Migohood. Cualquier otra marca comercial, marca de servicio, logotipo, nombre comercial y cualquier otra designación propietaria son marcas registradas o marcas comerciales de sus respectivos propietarios.

    <h4>Comentarios.</h4>

    Le agradecemos y animamos a que brinde comentarios, opiniones y sugerencias para mejorar la página web, la aplicación y los servicios Puede enviar comentarios por correo electrónico, a través de la página web y la aplicación, o por otros medios de comunicación. Usted reconoce y acepta que todos los comentarios que nos envíe serán propiedad única y exclusiva de Migohood y por el presente cede de manera irrevocable a Migohood y acepta ceder de manera irrevocable a Migohood todos sus derechos, título e intereses sobre todos los comentarios, incluyendo sin limitación todos los derechos de patente, derechos de autor, secretos comerciales, derechos morales y otros derechos de propiedad intelectual incluidos, y renuncia a cualquier derecho moral que pudiera tener sobre dichos comentarios. Bajo solicitud de Migohood y corriendo Migohood con los gastos, firmará documentos y dará más pasos según pueda solicitar razonablemente Migohood para ayudar a Migohood a adquirir, perfeccionar y mantener sus derechos de propiedad intelectual y otras protecciones legales para los comentarios.

    <h4>Política de derechos de autor.</h4>
    Migohood respeta la ley de derechos de autor y espera que sus usuarios hagan lo mismo. Es política de Migohood cesar y suspender en las circunstancias apropiadas las cuentas de Migohood de usuarios y de otros titulares de cuentas que repetidamente infrinjan o se crea que hayan infringido repetidamente los derechos de los titulares de los derechos de autor.

    <h4>Suspensión, terminación y cancelación de cuenta de Migohood.</h4>
    Nosotros podemos, bajo nuestro criterio y sin responsabilidad a usted, con o sin causa, con o sin aviso previo y en cualquier momento, decidir limitar, suspender, desactivar o cancelar su cuenta de Migohood. Si ejercitamos este derecho conforme a estos términos, todas o alguna de las consecuencias que a continuación se enumeran podrán tener lugar, con o sin preaviso o explicaciones a usted:  su cuenta de Migohood quedará desactivada o suspendida, su contraseña será desactivada, y no podrá acceder a la página web, la aplicación, nuestros servicios, su cuenta de Migohood o sus contenidos de miembro, ni recibir asistencia del servicio al cliente de Migohood, todas las reservas futuras pendientes o aceptadas, ya sea como usuario o como cliente, quedarán inmediatamente canceladas, podremos comunicar a sus usuarios o clientes que se ha cancelado una reserva potencial o confirmada, podremos reembolsar íntegramente a sus clientes todas las reservas confirmadas, con independencia de las políticas de cancelación preexistentes, podremos contactar con sus clientes para informarles sobre posibles alojamientos alternativos con otros usuarios que puedan haber disponibles en el página web, la aplicación y los servicios y de la misma manera para la prestación de los servicios, y usted no tendrá derecho a ninguna indemnización por las reservas (incluso las confirmadas) que hayan sido canceladas como consecuencia de una suspensión, desactivación o cancelación de su cuenta de Migohood. Usted puede cancelar su cuenta de Migohood en cualquier momento o enviándonos un correo electrónico. Tenga en cuenta que si se cancela su cuenta de Migohood, no tenemos la obligación de eliminar o devolverle ningún contenido que haya publicado en la página web, la aplicación y los servicios, incluyendo, entre otros toda crítica o comentario.

    <h4>Exenciones de responsabilidad.</h4>
    Si usted decide utilizar la página web, la aplicación, los servicios o los contenidos colectivos, lo hace bajo su propio riesgo, exclusivamente. Usted reconoce y acepta que Migohood no tiene obligación de realizar comprobaciones de antecedentes o de agresiones sexuales de ningún miembro, incluyendo entre otros, los usuarios y clientes, pero puede realizar dichas comprobaciones de antecedentes o agresiones sexuales si así lo considera Migohood. La página web, la aplicación, los servicios, los contenidos se ofrecen sin garantía de ningún tipo, ni expresa ni tacita. Sin limitar lo anterior, Migohood rechaza expresamente cualquier garantía de comerciabilidad, idoneidad para un propósito particular, uso, disfrute o exoneración de infracción y cualquier garantía que surja del curso de comercio o uso de la transacción, Migohood no ofrece ninguna garantía de que la página web, la aplicación, los servicios, los contenidos, incluyendo entre otros, las ofertas de alojamiento o servicio, satisfagan sus requisitos o estén disponibles de manera ininterrumpida, segura y libre de errores.
    Migohood no ofrece ninguna garantía sobre la calidad de las ofertas de alojamiento o prestación de servicio, usuarios, clientes, su acumulación de créditos de alojamiento o servicio, los servicios o contenidos, o la precisión, puntualidad, verosimilitud, integridad o fiabilidad de cualquier contenido  que se obtenga a través de la página web, la aplicación los servicios o los créditos de alojamiento o servicio.
    Ningún consejo o información, ya sea oral o escrito, que se obtenga por parte de Migohood o a través  de la página web, la aplicación, los servicios o el contenido constituirán ninguna garantía, ni expresa ni tácitamente.
    Usted es responsable exclusivamente de todas sus comunicaciones e interacciones con otros usuarios de la página web, la aplicación o los servicios y con otras personas con quien usted se comunique o interactúe como resultado del uso de la página web, la aplicación o los servicios, incluyendo usuarios y clientes entre otros.
    Usted entiende que Migohood no hace ningún intento para verificar las declaraciones de los usuarios de la página web, la aplicación o los servicios, ni para revisar o visitar ningún alojamiento o verificar la prestación de un servicio.  Migohood no hace ninguna declaración ni garantía en cuanto a la conducta de los usuarios de la página web, la aplicación o los servicios, ni de su compatibilidad con cualquier usuario actual o futuro de la página web, la aplicación o los servicios.
    Usted acepta tomar las precauciones razonables en todas las comunicaciones e interacciones con otros usuarios de la página web, aplicación o los servicios, y con otras personas que se comunique o interactúe como resultado de su uso de la página web, la aplicación o los servicios, incluyendo usuarios y clientes entre otros, especialmente si decide conocerlos fuera de internet o personalmente, con independencia de que dichos encuentros sean organizados por Migohood. Sin perjuicio de la designación de Migohood como agente de cobros limitado d los usuarios al objeto de aceptar los pagos de los clientes en nombre y representación de los usuarios, Migohood declara expresamente que no asume responsabilidad alguna por la acción u omisión de los usuarios con respecto a los clientes o terceros, y así usted lo acepta.

    <h4>Limitación de responsabilidad.</h4>
    Usted acepta que hasta donde la ley lo  permita, usted asume todos los riesgos derivados de su acceso y uso de la página web, la aplicación, los servicios y los contenidos, las ofertas de alojamiento o servicio, la reserva de cualquier alojamiento o servicio, así como cualquier contacto que tenga con otros usuarios de Migohood, ya sea en persona o por internet, ni Migohood ni ninguna otra parte implicada en la creación, producción o entrega de la página web, de la aplicación, de los servicios, de los contenidos será responsable de ningún daño incidental, especial, ejemplar o consiguiente, incluyendo beneficios perdidos, perdida de datos o perdida de buena voluntad, interrupción del servicio, daños informáticos o falla del sistema, o el coste de productos o servicios de sustitución, ni de ningún daño persona, lesiones corporales o angustia emocional que se derive de estos términos o esté ligado a los mismos, y que surja del uso de o de la incapacidad de utilizar la página web, la aplicación, los servicios, u otras personas con quien usted se comunique o interactúe como resultado de su uso de la página web, aplicación, los servicios, las publicaciones o las reservas de alojamientos y servicios a través de la página web, la aplicación y los servicios de Migohood, ya sea en base en garantía, contrato, agravio, responsabilidad de producto o cualquier otra teoría legal, y haya sido o no informado Migohood de la posibilidad de dicho daño, incluso si se declara que un recurso legal limitado ha fallado.

    <h4>Indemnización.</h4>
    Usted acepta liberar, defender, indemnizar y exonerar a Migohood y sus afiliados y subsidiarias, y sus representantes, directivos, empleados y agentes de toda reclamación, responsabilidad, daños, pérdidas y gastos, incluyendo, entre otros, tarifas legales y de contabilidad razonables, que surjan de o estén de alguna manera conectadas su acceso o uso de la página web, la aplicación, los Servicios, los contenidos colectivos o su infracción de estos términos; su contenido de miembro; su interacción con cualquier miembro, reserva de un alojamiento o servicio, o  la publicación de un alojamiento o servicio; el uso, la condición o el alquiler de un alojamiento por su parte, incluyendo, entre otros, toda lesión, pérdida o daño (compensatorio, directo, incidental, consiguiente u otro) de cualquier tipo que surja en conexión con, o como resultado de, un alquiler, reserva o uso de un alojamiento o prestación de un servicio, y su acumulación de créditos de alojamiento o servicio de Migohood.

    <h4>Control de exportaciones y países con restricciones.</h4>
    Usted no puede utilizar, exportar, reexportar, importar o transferir la Aplicación, salvo en la medida en que lo autoricen la legislación de los Estados Unidos, las leyes de la jurisdicción en que se haya obtenido la aplicación y cualquier otra legislación aplicable. En particular, pero sin limitación, la aplicación no podrá ser exportada o reexportada: a países sujetos a embargos de los Estados Unidos; o a personas que figuren en la Lista de Personas Especialmente Designadas del Departamento del Tesoro de los EE. UU. o en la Lista de Partes Denegadas del Departamento de Comercio de los EE. UU. Al utilizar la página, la aplicación y los servicios, usted declara y garantiza que ni usted ni su alojamiento se localiza en un país sujeto a embargo por parte del Gobierno de los EE. UU. O que haya sido designado por el Gobierno de los EE. UU. como un país que "apoya el terrorismo" y que no se encuentra en ninguna lista de partes prohibidas o restringidas. Asimismo, no utilizará la página web, la aplicación ni los servicios para ningún fin que esté prohibido por la ley de los EE. UU., incluyendo el desarrollo, el diseño, la fabricación o la producción de misiles o de armas nucleares, químicas o biológicas. Migohood no autoriza las ofertas asociadas a ciertos países debido a las restricciones derivadas de embargos impuestos por los EE. UU.

    <h4>Cesión.</h4>
    Usted no puede asignar ni transferir estos términos, haciendo una operación de ley o de ninguna otra manera, sin el consentimiento previo por escrito de Migohood. Cualquier intento por su parte de asignar o transferir los términos de Migohood, sin dicho consentimiento, será nulo y no tendrá ningún efecto. Migohood puede asignar o transferir estos términos, bajo su criterio exclusivo y sin restricción. De conformidad con lo antedicho, estos términos serán vinculantes y fortalecerán los beneficios de las partes, sus sucesores y cesionarios autorizados.

    <h4>Avisos.</h4>
    Todos los avisos u otras comunicaciones permitidas o requeridas por el presente, incluyendo aquellas sobre modificaciones a estos términos, serán por escrito y Migohood los proporcionará a través de correo electrónico (en cada caso a la dirección que proporcione usted) o  con una publicación en la página web o a través de la aplicación. Para los avisos hechos por correo electrónico, la fecha de envió se considerará la fecha en la que se transmite dicho aviso.

    <h4>Ley de control y jurisdicción.</h4>
    Estos términos y el uso que usted haga de los servicios serán interpretados de acuerdo con las leyes de los Estados Unidos de América, con independencia de las disposiciones de conflicto de ley.

    <h4>Resolución de litigios.</h4>
    Usted y Migohood acuerdan que cualquier disputa, controversia o reclamación planteada o relacionada con estos términos, o el incumplimiento, resolución, ejecución, interpretación o terminación de los mismos, o con el uso de los servicios o el uso de la página web o la aplicación se dirimirán mediante arbitraje vinculante, si bien cada parte se reserva el derecho de solicitar medidas cautelares o compensación equitativa ante un tribunal con jurisdicción competente para impedir la contravención, apropiación indebida o violación de los derechos de autor, marcas comerciales, secretos comerciales, patentes u otros derechos de propiedad intelectual, así como la amenaza de que estos se produzcan. Usted acepta y conviene que tanto usted como Migohood renuncian al derecho a juicio ante jurado o a participar como demandante o miembro conjunto en un juicio de acción conjunta o en un procedimiento representativo. Asimismo, a menos que tanto usted como Migohood acuerden lo contrario por escrito, el árbitro no podrá consolidar las demandas de más de una persona y no podrá presidir ningún tipo de acción conjunta o procedimiento representativo.  En caso de que este párrafo específico fuese inaplicable, se considerará nula la totalidad de esta sección de "Resolución de litigios". A excepción de lo estipulado en la frase precedente, la presente sección de "resolución de litigios" seguirá vigente aún después de la resolución de estos términos.

    <h4>Reglamento de arbitraje y legislación aplicable.</h4>
    El arbitraje será administrado por la Asociación Americana de Arbitraje (American Arbitration Association, "A.A.A.") de conformidad con las normas de arbitraje comercial y los procedimientos complementarios para litigios relativos a los consumidores que sean de aplicación, salvo en la medida de lo modificado por esta sección de resolución de litigios. La Ley federal de arbitraje la interpretación y la aplicación de esta Sección en Estados Unidos. Para el caso de Colombia se realizara en los centros de Arbitramento de la Cámara de Comercio de Santa Marta (Magdalena). Y para otros países se realizara en los Centros de Arbitramento correspondientes. Usted acepta que será en estos centros de arbitramento donde se resolverán los litigios o conflictos legales y no es otro lugar.
    Proceso de arbitraje. Si una parte desea iniciar un arbitraje, esta deberá facilitar a la otra parte una solicitud de arbitraje por escrito según estipulan las normas de la A.A.A. (La A.A.A. facilita un formulario de solicitud de arbitraje así como un formulario distinto para los residentes en el Estado de California). Podrá actuar como árbitro tanto un juez retirado como un abogado autorizado para ejercer, y será elegido por las partes de entre los árbitros que consten en la lista de árbitros para litigios en materia de consumo de la A.A.A. en el caso de Estados Unidos. Si las partes no logran ponerse de acuerdo para la elección de un árbitro transcurridos siete (7) días tras la entrega de la solicitud de arbitraje, la A.A.A. nombrará al árbitro de conformidad con las normas de la A.A.A.
    Lugar y procedimiento de arbitraje. A menos que usted y Migohood decidan otra cosa, el arbitraje se realizará en su lugar de residencia. Si su demanda no sobrepasa los 10 000 USD, el arbitraje se realizará exclusivamente a partir de los documentos que usted y Migohood faciliten al árbitro, a menos que usted solicite una audiencia o que el árbitro estime que es necesaria una audiencia. Si su demanda excede de los 10 000 USD, se determinará su derecho a una audiencia de conformidad con las normas de la A.A.A. Con sujeción a las normas de la A.A.A, el árbitro podrá, según su criterio, conducir un intercambio de información razonable entre las partes, que sea coherente con el carácter acelerado del procedimiento de arbitraje.
    La decisión del árbitro. El árbitro dictará un laudo en el plazo estipulado por las normas de la A.A.A. La decisión del árbitro incluirá los resultados y conclusiones esenciales en que haya basado el laudo. Este se podrá presentar como una decisión en cualquier tribunal de jurisdicción competente. La indemnización por daños y prejuicios determinada por el árbitro deberá ser coherente con lo estipulado más arriba en la sección de "exención de responsabilidad", en lo que respecta al tipo y la cantidad de los daños de que puede ser responsable una de las partes y de igual forma en el caso de los litigios que se resuelvan el Colombia y otros países. El árbitro podrá emitir una orden de reparación de agravios o medidas cautelares solo a favor del demandante y solo en la medida en que sea necesario para otorgar un resarcimiento justificado a la demanda individual del demandante.

    <h4>Cambios relativos a la resolución de litigios.</h4>
    Sin perjuicio de otras disposiciones de estos términos, si Migohood modifica su sección de “Resolución de litigios” con posterioridad a la fecha en que usted haya aceptado inicialmente los presentes términos (o haya aceptado cualquier modificación posterior de estos términos), usted puede rechazar dicho cambio enviándonos una notificación por escrito (también válida por correo electrónico ) en el plazo de 30 días a partir de la fecha de entrada en vigor de dicho cambio, según se indica en la "fecha de la última actualización" mencionada previamente o en la fecha del último correo electrónico que Migohood le haya enviado con la notificación de dicho cambio. Al rechazar cualquier cambio, usted acepta el arbitraje de cualquier litigio surgido entre usted y Migohood con arreglo a las disposiciones de la presente sección de "Resolución de litigios", a partir de la fecha de aceptación de estos términos (o de aceptación de cualquier modificación posterior de estos Términos).

    <h4>Generalidades.</h4>
    El hecho de que no se haga uso por parte de Migohood de cualquier derecho o disposición incluido en estos términos no constituye una renuncia al uso futuro de dichos derechos o disposiciones. Una renuncia a dichos derechos o disposiciones solo será efectiva si se realiza por escrito y está firmada por un representante de Migohood debidamente autorizado. A menos que se estipule de manera explícita en los presentes términos, la interposición por cualquiera de las partes de cualquiera de los recursos que le corresponden con arreglo a los presentes términos se entenderá sin perjuicio de las demás formas de reparación que le correspondan con arreglo a estos términos o de otro modo. Si, por cualquier motivo, un árbitro o un tribunal de jurisdicción competente determinan que cualquier disposición de estos términos no es válida o no es posible aplicarla, esa disposición será aplicada en todo lo permisible y las otras disposiciones de estos términos permanecerán en aplicación y efectos completos.
    Estos términos no otorgan y no pretenden otorgar ningún derecho a otras personas que no sean las partes. Sin perjuicio de lo anterior, las partes acuerdan que las redes de tarjetas de pago son terceros beneficiarios de estos términos a efectos de hacer cumplir las disposiciones relativas a los pagos, pero que su consentimiento o acuerdo no es necesario para ningún cambio o modificación de estos términos.
    Estos términos constituyen el entendimiento y acuerdo completo y exclusivo entre Migohood y usted sobre la página web, la aplicación, los servicios, los contenidos colectivos y cualquier reserva o listado de alojamiento y servicios realizados a través de la página web, la aplicación y los servicios. Para todos los efectos debe diferenciarse entre los servicios que prestan los usuarios y los  servicios que presta Migohood.

    <br><br><strong>* Sobre alguna duda sobre estos términos y condiciones de uso, puede contactar a Migohood.</strong>


  </div>
</div>



@stop
