@extends('layouts.help')
@section('title', 'Terms and Conditions')
@section('first', 'Terms and Conditions')
@section('second', 'About our Legal Terms and Privacy Pocy')
@section('content')
<div class="box">
  <div class="right">
    <a href="{{ url('/terms') }}" class="active">EN</a>
    <a href="{{ url('/terms_es') }}">ES</a>
  </div>
  <div class="box-body">
    <strong>By accepting the terms and conditions of use you understand that:</strong>
    <ul>
      <li><strong>1.</strong> Users should always consult the local and national laws of each country for providing different kinds of services and shall not use the platform for illegal activities.</li>
      <li><strong>2.</strong> Users may not make any claim against Migohood, but against user caused by their actions or omissions injury.</li>
      <li><strong>3.</strong> The platform respect the differences of sex, race, national or family origin, language, religion, political or philosophical opinion and provide the same treatment without discrimination on grounds of sex, race, national or family origin, language, religion, political opinion or philosophical.</li>
      <li><strong>4.</strong> Migohood Reserves the right to reserve the right to modify the site, application, or services, and change the terms and conditions, including fees for services at any time and without notice. The changes will be posted on the platform or by any other means. If the user continues to use and access the platform after publication of the modification, the user is understood to agree to be continuing registered on the page or application If you do not accept the terms and conditions of use, you can stop using Platform or close your profile .</li>
      <li><strong>5.</strong> Only they can become registered users over 18 years.</li>
      <li><strong>6.</strong> To offer a service or make a reservation you must be registered on the platform.</li>
      <li><strong>7.</strong> Migohood is not the owner or operator of real estate or furniture to be used in the provision of services that are offered in the platform nor acts as agent for owners or operators of real or personal property used in the provision of services that are offered in the platform.</li>
      <li><strong>8.</strong> Migohood facilitates the availability of website, application and related services and acts as a limited agent of each user charges.</li>
      <li><strong>9.</strong> Migohood not responsible for the content that users post through their profiles.</li>
      <li><strong>10.</strong> Migohood is not responsible for the reservations made or accepted through this platform. It is the sole responsibility of users. Similarly users are solely responsible for their acts or omissions before, during and after the provision of services between them.</li>
      <li><strong>11.</strong> Migohood is not responsible for any damage or injury resulting from interactions between users.</li>
      <li><strong>12.</strong> Migohood recommended that users employ adequate insurance to their services and offers advice on the subject according to each country.</li>
      <li><strong>13.</strong> Migohood can offer users the choice of a photographer to make pictures of their services and thus verify Migohood through images of their profile. All pictures taken by photographers of Migohood be Migohood property and may be used by the company for business purposes among others.</li>
      <li><strong>14.</strong> All members can donate the amount of money they choose, these grants will be transferred to the Foundation Migohood, which aims for promoting social and business development of those entrepreneurs willing to innovate and to the wider community and generate profits to the community in various orders as cultural, recreational, sporting and others</li>
    </ul>

    <h4>User behavior.</h4>
    You acknowledge and agree that you assume full responsibility for complying with the laws, rules and regulations as well as with tax obligations applicable to your use of the website, application, services and content. In connection with your use of the website, application, services and content, and you can not accept that you will not:
    infringes any applicable law or regulation, state, provincial, national or otherwise, or any court order, including, without limitation, planning restrictions and tax regulations; will use computer programs, devices, robots, backdoors or other means or manual or automatic to access, extract, collect or analyze content of any website or other hosted service on the web page, in the application, services processes, or in collective content;
    you access or use our website, application, services or API Migohood to use, display or permit the use or expose any content Migohood not be publicly displayed by Migohood in their pages or search results Accommodation Sites and services before confirmation of a reservation; It is inconsistent in any way with the Privacy Policy of Migohood or service conditions; or otherwise violates the privacy rights or any other rights of users Migohood or any third party;
    will use the website, application, services or collective content for commercial or other not expressly authorized in these terms end; He copied, stored, accessed or otherwise use any information held on the website, application, services or content groups for purposes that are not explicitly authorized in these terms;
    infringes the rights of any person or entity, including without limitation, intellectual property, privacy, publicity or contractual rights; interfere with, or will damage our website, application or service, including without limitation through the use of viruses, bots cancellation, Trojan horses, malicious code, invasion of packages, Denial of Service, backdoors, packet spoofing or IP, routes or falsified information email address or similar methods or technology;
    will use our website, application or services to transmit, distribute, publish or provide any related information with any other person or entity, including without limitation, photographs of others without their permission, personal contact information or account numbers or credit cards, debit or calls;
    will use our website, application, services or content groups in connection with the distribution of unsolicited commercial email ("spam") or not related to accommodation in a private home advertising; "It besiege" or harass any other user of our website, application, service or collective contents nor collect or store any personally identifiable information about any other user transactions for purposes other than as a customer or user of Migohood;
    will offer, as a user, any accommodation yourself not own or have permission to rent as residential property or other (without limiting the foregoing, you will not offer accommodation like yours if acting in the capacity of agent or rental agent a third);
    will offer, as a user, any property that can not be rented or sublet in connection with the terms and conditions of an agreement with a third party, including, among others, a lease of property; It will be registered in more than one account Migohood or register with Migohood account on behalf of a person other than yourself;
    except with the express permission of Migohood, request or reserve a stay in an accommodation if it is not you who will stay in said housing; will contact with a user for any purpose other than to ask a question related to a reserve or accommodation and services involved.
    will contact a customer by no other than ask you a question related to a reserve or that customer use of the site, application and services involved; will recruit or otherwise require any user or another member to join services or third party websites that are Migohood competition, without the prior written approval of Migohood;
    it will impersonate any person or entity, or falsify or otherwise falsely represent yourself or your affiliation with any person or entity; will use automated scripts to collect information or otherwise interact with any website, application, services or content groups;
    will use the site, application, services or collective contents to find a user or customer and then made a reservation for self-catering accommodation on the page, the application or service to avoid the obligation to pay any service fees associated with the provision of services by Migohood or for any other purpose;
    submit any false or misleading information on prices or to publish a price that is not intended to sustain or meet;
    will hang, upload, post, send or transmit any content that: violate, appropriates or violates a patent, copyright, trademark, secret, moral rights or other intellectual property rights of a third party or rights of publicity or privacy ; violates, or encourages any conduct that would violate any applicable law or regulation or generate liability; is fraudulent, false, misleading or deceptive; is defamatory, obscene, pornographic, vulgar or offensive; promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; whether violent or threatening or promotes violence or actions which are threatening to any other person; or promotes illegal or harmful activities or substances;
    systematically retrieve data or other content of our website, application or service to create or compile, directly or indirectly, in one or multiple downloads, a collection, compilation, database, directory or the like, whether by manual methods, using robots, crawlers, spiders, or other;
    you will use, display, copy or frame the site, application, services or collective content or any individual element of the website, application, services or collective contents, the name of Migohood, any registered Migohood brand, logo or other proprietary information, or the design and layout of any page or form contained on a page on the website, application or services, without the express written consent of Migohood;
    you access, manipulate it or use non-public areas of the website, application or services, computer systems Migohood or technical delivery systems providers Migohood;
    will attempt to probe, scan or test the vulnerability of any system or network Migohood, nor violate any security or authentication measures;
    He avoided surround, remove, deactivate, disable, disassemble or in any other way will dodge any technological measure applied by Mighood or any of the providers Migohood or other third party (including another user) to protect web page, service, application or collective content;
    It falsify any header TCP / IP packet or any part of the header information in any email or posting newsgroup, or in any way use the website, services, implementation or collective contents to send altered information, misleading or false identifying the source;
    will attempt to decipher, decompile, disassemble or reverse engineer any software used to deliver the web page, services, application or content groups;
    will defend, encourage or assist any third party in doing any of the above; or
    accept or make a payment of fees or service accommodation outside Migohood. If done, you acknowledge and agree that: will be in breach of these conditions; accept all risks and responsibility for such payment and Migohood exempt from any liability for such payment.
    You migohood have the right to investigate and prosecute violations of any of the foregoing in any way permitted by law.
    Migohood may access, preserve, and disclose your information when required by law or when we believe in good faith that it is reasonably necessary to respond to complaints against Migohood, or to comply with the provisions of any judicial notification (eg, citations or court order), enforce or administer our agreements with users, such as the present conditions, or prevent fraud, risk assessment, conduct research, customer support, product development or debugging purposes, or protect the rights, property or safety of Migohood, its users or the general public. You agree that Migohood has no obligation to monitor your access to or use of the website, application, services or collective or review or edit any Member Content contained, but has the right to do so in order to make operate and improve the site, application and services (including, without limitation, in order to prevent fraudulent activities, risk assessment, conduct research and provide customer support), ensure compliance with these terms, follow the law applicable or the order or requirement of a court, administrative agency or other governmental entity, responding to content it deems questionable in some way or as stipulated in these conditions. Migohood reserves the right at any time and without notice, to remove or disable access to any content that Migohood group, in its sole discretion, considers to be questionable for any reason, violates these terms or otherwise is harmful for website, application or services.

    <h4>About misconduct.</h4>
    If you are staying with, or hosting someone who you believe is acting or has acted inappropriately, including, among others, anyone who engages in offensive, violent or sexually inappropriate behavior, suspect that stolen, or get involved in any other misconduct, you should immediately report such person to the appropriate authorities and then Migohood by contacting local police authority; provided that their complaint did not force us to take any action beyond what the law required, if any, will not incur any liability to you.

    <br><br><strong>IN CASE OF EMERGENCY.</strong> Migohood sends emails automatically to users of the site concerned. Users can also try to communicate with other users who are in the affected area, depending on the type of emergency. Users can host and provide services to other users for free for the duration of the emergency.
    It is advisable to call local authorities as firefighters, police, ambulance, hospitals and any kind of citizen service center, and the embassies and consulates of their countries of origin, as appropriate.

     <h4>On financial terms.</h4>

    Accommodation fee or service user: amounts required to pay a user-client in exchange for their stay in accommodation or providing a service. It is the user-host exclusively Migohood not responsible for the accommodation rates offered. The host can decide user- exclusively, these amounts include a cleaning fee or any other permitted rate at Migohood platform, or other values ​​that determines the host user must charge.
    Customer rate: rate that Migohood user-charges a customer for the use of services based on a percentage of the property or service fees apply. Customer rates will be displayed to the user-client when you are prompted to send a reservation request to a user-host.
    User rate: rate that Migohood charges a user-host by using the services based on a percentage of the property or service fees apply. User charges are displayed to the user when prompted to confirm or refuse a reservation request from a potential customer.
    Migohood service fees sum of the rates of user-client and user fees-host.
    Total rates: sum of accommodation rates or service user, and user fees plus tax.

    <h4>Reservations and financial terms of users and customers</h4>

    If you are a user and a reservation for accommodation or other services through the website, application or service is requested, you shall be required to confirm or reject the reservation request within the reservation request. Otherwise, the reservation request is automatically canceled.
    When a reservation is requested through the website, the application will share with you: the name and surname of the user who requested the reservation, a link to the profile page of the user account Migohood-customer.
    Migohood the total fees charged at the time of the confirmation (that is, when the user-host confirms that it accepts the request for the reservation) and start paying fees of accommodation and other services (less user fees host-to Migohood and any taxes paid with respect to user fees-host, for example, VAT in Colombia or Europe) the user-host in less than 24 hours from the moment the user-customer arrives accommodation or start the corresponding service (except to the extent that a return is due to the user-client). The time the user-host soon receive payments depend on the payment method you choose. Some of these methods involve the participation of third party payment processors that can force the user-host their own additional fees for the use of its services, including the deduction of such fees from the amount of payment.
    If you owe or undertakes to pay any amount through Migohood (either as a result of their reserves or acts as a client or otherwise), Migohood may, but not obliged, to retain the amount due to Migohood any payment due to you as a user, and the amount withheld to offset the amount owed by you to Migohood. If Migohood comes from the manner indicated above, the liability assumed by you against Migohood be extinguished to the extent of the amount retained by Migohood and Migohood no further obligation or responsibility to you, with respect to the amount withheld. In addition to the amount due, if your account is delinquent or entitled to refunds on your account, you will be able to charge ancillary fees in addition to our collection by such overdue amounts or refunds. Such fees or charges may include collection rates, commissions or other third-party charges. You hereby expressly agree that all communication regarding delinquent accounts will be made by mail or phone, as provided Migohood. Such communication may be made by Migohood or someone on your behalf, including among others, a third party billing agent.
    The user names Migohood as limited user charges for the exclusive purpose of accepting the accommodation rates and other service users agent.
    You agree to consider customer payments made through Migohood as having been paid directly to the user, so the user will have the property or service to customers in the form previously agreed as if the user had received fees accommodation or service user. You agree that Migohood may, according to the cancellation policy set by the user allowing the customer to cancel the reservation and return to the client (through Migohood) the portion of the hosting fees or service specified in the applicable cancellation policy.
    Users understand that since Migohood accept payments from customers as limited to those users authorized agent and that the obligation to make the payments Migohood the user is subject to and conditional upon actual receipt of related payments from customers. Migohood not guarantee payments to users in respect of those amounts which are not actually received from customers for Migohood. In accepting his appointment as limited user authorized agent Migohood assumes no responsibility for the actions or omissions of the user.

    <h4>Reservations and financial terms for customers.</h4>
    Users not Migohood are solely responsible to respect all confirmed reservation and make available all or accommodation booked through the website service, application and services. If you, as a customer, choose to sign a transaction with a user for booking accommodation or other services, you agree and understand that it will be forced to sign a user agreement and you agree to accept these terms, conditions, rules and restrictions associated with said housing taxes or service user.
    You acknowledge and agree that you, and not Migohood, will be responsible for fulfilling the obligations of the agreements, which Migohood is not part of those agreements and that, except for payment obligations hereby contracts, Migohood declared exempt from all liability in connection with those agreements. You acknowledge and agree that although Migohood is not part of the agreement between you and the user, Migohood acts as collection agent user for the sole purpose of accepting on behalf of user payments you make. When you pay the total fees Migohood its obligation to pay the hosting fees or service to the user is extinguished, and Migohood is responsible for transferring the user fees or service accommodation.
    The total fees to be paid will be shown to the customer before it send your reservation request. As noted above, the user is required to confirm or reject the reservation request within the period of application of the reservation, otherwise, the requested reservation will be canceled. If a requested book (this is not confirmed by the applicable user) is canceled, all amounts received by Migohood be refunded to that customer, depending on the selections made by the customer through the website and the application, and all pre-authorization of the credit card of the Customer will be released, if applicable.
    You, the customer, agree to pay Migohood reservations requested in connection with your account Migohood requested if such reservations are confirmed by the relevant user.
    To establish a reserve pending confirmation of your reservation requested by the relevant user, you understand and agree that Migohood, on behalf of the user, reserves the right, in its sole discretion, to obtain a referral through your credit card for the total fees or charge your credit card a nominal amount not to exceed one dollar (1 USD), or a similar amount in the currency in which you are making the transaction (for example, a euro or sterling) to verify your credit card.
    Generally, Migohood raise the total fees owed once Migohood receive confirmation by the relevant user; if necessary, the total fees may be levied at a later time. Note that Migohood can not control any fees that may be charged to a customer by their bank in connection with the collection of Migohood of the total fees, and Migohood is not liable in any way on these charges by the bank .
    In connection with the requested reservation, you will be asked to provide regular billing information such as name, billing address and credit card information either Migohood or his / s processor / is third-party payment. You agree to pay all Migohood confirmed reservation made in connection with your account Migohood under these terms by one of the methods described on the website or application, for example, by PayPal or credit card. You hereby authorize the collection of such amounts by loading the credit card provided as part of the application of the reserve, either directly by Migohood or indirectly through an Internet payment processor by third parties or by one of the payment methods described on the website or application. You also authorize Migohood charge your credit card in case of damage to the property as provided in the "Damage to Lodging" section and security deposit, if applicable. If you are directed to the processor or processors Migohood third party payments, the terms and conditions governing the use of such third party service and collection practices of such third party personal information you may be subject. Check these terms and conditions and privacy policy before using the services. Once your reservation confirmed transaction is complete, you will receive a confirmation email summarizing your confirmed reservation.

    <h4>Security deposits.</h4>
    Users can choose to include security deposits as a condition to accept a reservation for accommodation or providing a service. If you include as a condition for a security deposit of a reservation of accommodation or service user, and a user claims that security deposit, Migohood, in its capacity as collection agent user will use commercially reasonable efforts to charge the amount of payment method the customer calls up, within a period after the client's departure accommodation or termination of the provision of a service by a user reasonable time. It migohood also use its commercially reasonable efforts to respond to requests and complaints regarding deposits in users but Migohood is not responsible for managing or accept any claim by the related security deposits and rejects all users and each of the responsibilities in this regard.

    <h4>Rates Migohood services.</h4>
    In consideration for the use of the platform Migohood, Migohood charges service fees. Where applicable, you can also collect taxes with respect to user fees and customer fees. Migohood user fees deducted from the accommodation rates or service user before remitting the balance to the user as described in these terms. Client fees are included in the total fees.
    Migohood balances transferred to users via check, PayPal, direct entry, or other methods of payment, as described on the website or through the application, in the currency chosen by the user, depending on the selections made by the user through the website, application and services. Amounts are rounded up according to the policy of rapprochement.
    Note that Migohood may impose or deduct processing costs of foreign currency with respect to any payments or disbursements made by Migohood in currencies other than the US dollar. Except as otherwise contemplated in the present, the service fees are non-refundable.

    <h4>Financial conditions and general reserves</h4>
    If you, as a customer, cancel your reservation requested before booking request is confirmed by the user, Migohood canceled pre-authorization of your credit card and / or return nominal amounts charged to your credit card in connection with the requested reservation within a commercially reasonable time.
    If, as a customer, you want to cancel a confirmed through the booking website, application and services, both before and after arriving at the accommodation or before or after the provision of a service, the cancellation policy the user will applied to such cancellation. Our ability to repay housing fees and other amounts charged to your account will depend on the terms and conditions of the cancellation policy applicable. On the website and in implementing more information on the return of amounts and cancellation policy. The customer fee is non-refundable regardless of cancellation policy selected by the user.
    If a user cancels a confirmed reservation made through the website, and application services, Migohood reimburse the total fees of the reserve to the relevant customer within a commercially reasonable time of the cancellation and the customer will receive an email or other confirmation from Migohood other alternatives and other related information. If a user has canceled a confirmed reservation and you, as a client, has not received any email or other communication Migohood, contact Migohood.
    If, as a user, you cancel a confirmed booking, you agree that Migohood may apply sanctions or take measures, including automatically publish an assessment indicating that a reservation is canceled, keep your calendar unavailable or blocked during the dates of the booking canceled, or impose a cancellation fee (which will be withheld from your future payments or will be charged in the credit card registered to your account Migohood). Before you decide to cancel a reservation you will be informed of the situations in which a cancellation fee applies.
    In certain circumstances, Migohood may, in its sole discretion, is necessary or desirable to cancel a confirmed reservation made through the website, application or services. This decision may be due to the reasons specified in the policy of force majeure or other reasons Migohood. Also Migohood may, in its sole discretion, determine the reimbursement to the client of all or part of the amounts charged to that client in accordance with the refund policy to clients. You agree that Migohood and the client or user in question will not be responsible in any way by such cancellations or refunds.
    If you still user, the customer cancels a confirmed reservation or Migohood decides it is necessary to cancel a confirmed reservation, and Migohood performs client restitution according to the refund policy you agree that, in case they have already been Migohood paid, Migohood entitled to recover the amount of reimbursement made to the customer, by subtracting that amount from any future accommodation fee is owed.

    <h4>Recurring payments</h4>
    In some cases, customers may be required to make payments for incremental recurrent and total fees to be a confirmed before the start of your stay in the relevant property or the provision of a reservation service will be made available to the public more information on recurring payments through the website, application and services, if applicable. If recurring payments are applied to a confirmed booking, the customer authorizes Migohood, on behalf of the user to charge the total fees and agree that such entity to the user to make payments in the amounts and frequency associated with applicable recurring payments, each identified in the Website, application and services.

    <h4>Approach.</h4>
    Migohood may, at its sole option, round up or down the amounts payable to / by customers or users to the closest whole number function in the relevant currency (for example, expresses the number of dollars, euros or other supported currencies); eg Migohood rounded the amount of $ 101.50 to $ 102.00, and $ 101.49 to $ 101.00.
    Some currencies are expressed with very high figures. In these cases, Migohood may determine that the functional base unit in which these currencies are denominated will be 10, 100 or 1,000. Corresponding examples for such Migohood the currency would be for an amount of 1045-1050 and 1044-1040, or from 35,450 to 35,500 and 35,449 to 35,400, or 837,500 to 838,000 and from 837,499 to 837,000.

    <h4>Errors in processing payments.</h4>
    We will take action to correct any error in the processing of payments that we know about. Such measures may include the realization of a credit or a debit (as appropriate) with the same method of payment used for the original payment to or by you, so that you end up receiving or paying the correct amount.

    <h4>Donations.</h4>
    Users can make a donation to the portion of funds they receive confirmed reservations made through the web site, application and services Migohood Foundation. We do not accept any responsibility or obligation, if the user actually makes donation has promised to do. In these cases, the user in question will be responsible for complying with laws and regulations that may apply to such gifts and / or fundraising activities.

    <h4>Taxes.</h4>
    Tax regulations may require us to apply the relevant tax information to our users or practicing the mandatory withholding tax on the amounts paid to users, or to adopt both measures. For example, the rules of the US tax authorities (IRS) states are required to apply for W-9 IRS Form our users living in the United States and the corresponding form W-8 (ie, the Form W-8BEN ) IRS to non-resident users in the United States offering accommodation in United States. You, as a user, are solely responsible for maintaining the information in their tax returns, current, complete and correct. If you, as a user, not give us the documents we deem necessary to fulfill our obligation (if any) withholding tax payments (for example, when a user you are resident in the United States and does not provide us Form W-9 IRS completed), we reserve the right at our discretion to withhold all payments that we should make in their favor until the matter is resolved, to practice deductions established by law, or to adopt both measures.
    You, as a user, understand and agree that you are solely responsible for determining their reporting requirements applicable taxes, and taxes to be included and include taxes to be recovered or liabilities related to taxes. Also, you are responsible for submitting to the competent authorities all taxes or received by you. Migohood can not and does not offer tax advice related to any user.
    Where applicable, or at the request of a user, Migohood may issue a valid VAT invoice that user.
    You acknowledge and agree that administrations, departments or authorities country in which it is located your accommodation may require the practice to customers or users applicable withholding tax on the amounts paid for the right to use and / or occupy accommodation and the amounts withheld to the competent tax authorities are entered. Although laws vary across jurisdictions, it may be required that those sums are retained and entered as a percentage of income or accommodation rates set by users, such as a fixed amount per day or other modalities. These quantities are sometimes called "occupancy tax", "hotel taxes", "accommodation tax", "temporary tax", "sales tax or use", "value added tax", "tax room "or" tourist tax "(hereinafter the" occupancy tax ").

    <h4>Collection and Occupancy Tax Return.</h4>
    In certain jurisdictions, Migohood may elect, in its sole discretion, to facilitate the collection and reporting occupancy taxes on behalf of customers or users, in accordance with the instructions of this use contract terms and conditions provided when the tax jurisdiction concerned Migohood or users are obliged to collect and report the amounts mentioned. In any jurisdiction where we decide to collect and submit taxes directly or you client or user accepts the present instead of the user collects taxes occupancy customers and declare to the tax authority, is Migohood who occupancy taxes collected these customers on behalf of the user at the time that the tariffs for accommodation or service user is charged, and declare such occupancy taxes to the tax authorities. When Migohood declare taxes collected and occupation in one jurisdiction for the first time this circumstance Migohood notify users who then have published offers of accommodation in those jurisdictions.
    Customers and users can view separately in the documents of the transaction amount, if any, of taxes collected and held by Migohood occupation. When Migohood directly perform the collection and return, customers and users agree that users can not try to collect or raise taxes any occupation related to their accommodation in Migohood in that jurisdiction.
    You expressly agrees to release, defend, indemnify and hold Migohood, its affiliates and subsidiaries, their directors, officers, employees and agents harmless from any claims, liabilities, damages, losses, debts, liabilities and expenses, including among others, reasonable fees law and accountancy firms, arising from or relating in any way to occupancy taxes, including among others, its applicability, the calculation, collection or tax of occupation of any amount or of the total in relation to transactions or accommodations or services.
    In each jurisdiction in which we raise taxes and declare, users and customers give their express consent, without further notice, so that we store, we carry out the transfer and disclose to the tax authority data and other information relating to them or their transactions, reservations, lodging or occupancy taxes, services, including among others, the personal identifying information such as name of the user or client, accommodation addresses, dates and amounts of transactions numbers tax identification, the amount of taxes collected from customers or supposedly accrued, contact information or similar.

    <h4>Filing option by the user.</h4>
    In other jurisdictions, Migohood may, at its discretion, to raise the occupancy tax on behalf of users and customers in accordance with the instructions of the users to include in the booking process a specific item on the occupancy tax, by the user orders that occupancy taxes Customers are forwarded directly to the user for a declaration such taxes directly to the taxing authority. In any jurisdiction where we decide to raise using Option Tax Return by the user, whether you are a customer as a user, hereby directs and authorizes the user to recall Migohood occupancy taxes received from Customers upon receipt of hosting fees or service user, who is obliged to declare such taxes directly to the competent tax authority. If Migohood offers the option of Income Tax by the user and a user opts for it in any jurisdiction, users and customers will be solely responsible for the checkout of all and any taxes that may apply to accommodation or services the user.
     You agree and understand that Migohood is not responsible, and does not declare any occupancy tax to the tax authority had they chosen Option Tax Return by the user.
    For this, you agree that by third payment processors, Migohood is merely processing your choice to send directly occupancy taxes client for you to declare to the tax authority. You expressly agree to hold harmless, defend and indemnify Migohood, its affiliates and subsidiaries, and their directors, officers, employees and agents from any and all claims, liabilities and / or damages, losses, debts, liabilities and expenses, including but not limited to reasonable attorneys or accountants, arising out of or in any way connected with other employment taxes, including without limitation, implementation, assessment and collection of any part or all of the taxes occupation operations or units. In any jurisdiction in which we provide the option of Filing user, users and customers expressly authorize us, without further notice, to store, transfer and disclose to the competent tax authority data and other information, as well as their operations, reservations, accommodation and occupancy taxes or other, including personally identifiable information such as the name of the user or client, the addresses of the advertisements, the dates and amounts of the transactions, tax identification numbers, the amount of taxes supposedly received or accrued by client users, contact details and similar information.

    <h4>Various provisions concerning the occupancy tax.</h4>
    Whether you are a customer as if you are a user, you agree that any claim or any event giving rise to a claim related to the Option Tax Return by the user or the Revenue and Tax Return will be extended to any vendor or supplier that Migohood be used in connection with these tasks, if any. Guests, customers and users accept that we may demand the payment of additional amounts on the assumption that the taxes withheld and / or paid insufficient for you to comply fully with their obligations to the tax authorities, and agree that the only action you may exercise with respect to taxes withheld occupation will be to obtain reimbursement, by the competent tax authorities, occupancy taxes retained by Migohood in accordance with the applicable procedures established by those tax authorities.

    <h4>Foreign currency.</h4>
    Migohood platform facilitates bookings between clients and customers who prefer to pay and receive payments in various currencies, which may require that currency conversions suit different preferences currency. Although Migohood platform allows users to see the price of accommodation and services in various currencies, the foreign exchange available for users to make and receive payments may be limited, and may not include the default currency of a geographical area concreting.
    Each a Foreign currency conversion is processed at a conversion rate of foreign currency. In general, this type refers to the amount of one currency to be paid to buy a certain amount of another currency at a given time. For example, if it costs $ 125.00 to buy € 100.00, the currency conversion rate of US dollars to euros would be 1.25, and the currency conversion rate of US dollars to euros would be 0.8. Currency conversion rates vary every moment.

    <h4>Key definitions.</h4>
    "Display Currency" means the currency in which users see housing prices or service Migohood platform. Customers can choose and change the currency display to see prices for accommodation or service user supported in different currencies.</h4>
    "Reserve currency" means the currency in which a client must make payment of your reservation. At the time when the client submit the reservation request, the platform Migohood select the reserve currency, depending on the country of origin of the customer and payment methods available for that country. Migohood only supports certain currencies as reserve currencies. The reserve currency may be different from the currency of accommodation or service corresponding user.
    "List currency" means the currency in which prices are set accommodation or service. The currency of accommodation or service is set by the user.
    "Payment Currency" means the currency in which payment is paid to the user. The currency of payment is set by the user.
    "Exchange Rate Base" means the rate applied by Migohood throughout the system for the conversion of foreign currency and is applicable at the time the corresponding conversion of foreign currency, excluding any fee or extra charge claimed by Migohood is processed. Migohood sets the base rate change using information from one or more third parties.
    "Adjusted exchange rate" means the exchange rate that applies to the conversion of foreign currency and is calculated by adding a surcharge to the base rate change. This charge represents the tax Migohood margin in maintenance expenses and exchange rate risks.

    <h4>Currency conversions in Migohood platform.</h4>
    Migohood processed foreign currency conversion in the following situations:

    The display currency is different from the currency of accommodation or service when the client user sees a housing or service user: Migohood calculate the total fees estimated in the currency display, using either the base rate changes or exchange rate when set to display the total fees estimated in the currency of accommodation or service user. The adjusted exchange rate will apply if the currency display is a supported currency reserves, and is different from the currency of accommodation or service user. Otherwise, the base rate change is applied.
    The reserve currency is other than the currency of accommodation or service user when the client sends a request for reservation to accommodation or service user: Migohood calculate the total rates in the reserve currency by applying the exchange rate well base or adjusted exchange rate at time of the booking request to the total fees in the currency of accommodation or service. The customer can see the real exchange rate has been applied. Rates client, which are a percentage of the corresponding accommodation rates are calculated based on accommodation rates in the reserve currency (ie, after currency conversion accommodation or service is performed. The type of adjusted change will apply if the currency display is the same as the reserve currency, and is different from the currency of the accommodation or service. Otherwise, the base rate change is applied.
    The payment currency is different from the currency of Migohood when Migohood initiate a payment: as a rule, Migohood calculate the payment to be paid to the user, applying the base rate on the date on which Migohood start paying rates accommodations and services (less user fees and any applicable taxes Migohood to user fees, for example, VAT in Europe and Colombia) in the currency of Migohood. In cases where the payment method selected by the user involves the participation of a third payment processor (for example, Western Union) Migohood send the payment amount to the processor on a main currency (eg dollars American), applying the currency exchange rate for the housing or the main user base currency, the user can see the payment amount sent by Migohood in the main currency in the history of operations of the website or application, and calculate the actual payment processor that corresponds to the user using their own conversion rate corresponding to the principal currency against the foreign currency payment currency.
    When a confirmed booking is changed or canceled, and has made a conversion of foreign currency at the time of submitting the book: the conversion of foreign currency for any additional payments required of the customer or refund it will be processed using the same type the payment applied for the previous customer.
    When you, as a customer, send a reservation request for accommodation or service, you can see the real exchange rate used to calculate total rates in the reserve currency. When the adjusted exchange rate applies, you can see the charge included in the rate. The real exchange rate (and any charges included therein) shall also be indicated on the billing receipt book.
    Migohood updated regularly change the base rate, although it does in real time. In particular, Migohood not always modifies the base rate change immediately when expenses exchange rate variation experience. Accordingly, the base rate change may not be identical to the rate applicable and effective in the specific time converting foreign currency market is being processed.
    Note that the company that processed payments (for example, the transmitter from your bank or credit card company) will use a type conversion and may impose a fee for this, if your card or bank account is denominated in a different currency the reserve currency or the currency of payment, respectively. Similarly, the third party payment processors may also use a type conversion or conversion impose a fee on payments made. These fees and currency conversion fees are not known or controlled by Migohood.

    <h4>Privacy</h4>
    You agree that Migohood Privacy Policy (as amended from time to time) governs the collection and use of your personal information Migohood.

    <h4>Property</h4>
    The website, application, services and collective contents are protected by copyright, trademark and other laws of the United States and other foreign countries. You acknowledge and agree that the site, application and services and collective contents, including all associated intellectual property rights are the exclusive property of Migohood and its licensors. You will not remove, alter or obscure any copyright notice, trademark, service mark or other proprietary rights incorporated in or accompanying website, application, services or content groups

    <h4>Additional conditions.</h4>
    Our services offer different products and offers; so sometimes additional terms or product requirements shall apply to use these products. For example, additional conditions apply if you make a recommendation to Migohood new users. If the additional conditions are available to the relevant product or services you use, those additional terms become part of these conditions.

    <h4>Specific terms of housing loans or services.</h4>
    Housing loans or services may only be redeemed for confirmed through the website reserves, application and services, and after you accumulate credits for accommodation or services, such credits or housing services are automatically applied to your next confirmed reservation made through the website, application and services. Credits accommodation or services are only credits and have no monetary value and can not be returned or exchanged for cash. You can only redeem credits for housing or services after they are reflected in your account Migohood. The scope, variety and type of services and products that can be obtained by redeeming credits or accommodation services may change at any time.
    The credits expire three accommodations or services (4) years from the date the last loan of accommodation and services to accumulate in your account Migohood. Migohood will notify the email address you provide during registration account within thirty (30) days when the credits are scheduled to expire accommodation and services of their own. If for some reason you believe there is a discrepancy on the balance of housing loans and services, contact us. Migohood may require you to submit additional information to make a determination on your balance. All decisions are final and your balance low Migohood sole discretion. You are responsible for any tax consequences that may result from the conversion or use of credits of accommodation and services. Where applicable, Migohood may be required to account for VAT on some services for which credits are redeemed accommodation and services.
    Without limiting any of the provisions of these terms, and subject to applicable law, all accommodation and service credits expire Migohood if your account is terminated or suspended for any reason in the sole discretion of Migohood, or if Migohood interrupts the supply of the web page, application, services.

    <h4>License Application.</h4>
    Subject to compliance with these terms, Migohood granted a limited non-exclusive, non-transferable license to download and install a copy of the application on each mobile device or computer that is owned or controlled and run the copy of the application exclusively for your own personal use. Further, with respect to any application arising from the App Store), you only use the originating application in the App Store on Apple branded product that runs iOS (Apple's proprietary operating system) and as permitted by the established rules of use in the terms of service of the Apple App Store. Migohood all rights not expressly granted to you application so reserves by these terms.

    <h4>Access and download the application from iTunes.</h4>
    The following applies to any application that is accessed or downloaded from the Apple App Store:
     You acknowledge and agree that these terms are completed by you and Migohood only, not Apple. Migohood not Apple, is solely responsible for the application originating from the App Store and its contents. Your use of the source application in the App Store have to comply with the terms of the App Store service.
    You agree that Apple has no obligation whatsoever to provide maintenance and support services with respect to the originating application in the App Store.
    In the event that the application originating from the App Store breach of any applicable warranty, you may notify Apple, and Apple will refund the purchase price of the originating application in the App Store to you and everything that allows the applicable law, Apple will have no other warranty obligation whatsoever with respect to the originating application in the App Store. As between Migohood and Apple, all other claims, losses, liabilities, damages, costs or expenses attributable to any breach of any warranty shall be the sole responsibility of Migohood.
    You and Migohood agree that, as between Migohood and Apple, Apple is not responsible for resolving any claims that you have or any claim of any third party related to the application originating from the App Store or your possession and use of the application source in the App Store including, among others: product liability claims; any claim that the application originating from the App Store does not meet any applicable legal or regulatory requirements; and claims arising from consumer protection or similar legislation.
    You and Migohood accept that, in the case of a third party claim that the originating application in the App Store, or the possession and use of that application originating from the App Store, infringe those intellectual property rights of third equal between Migohood and Apple, Migohood, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any claim of infringement of intellectual property as required by these terms.
    You and Migohood accept and agree that Apple, and Apple's subsidiaries, are benefiting third of these terms as it relates to your license application originating from the App Store, and after acceptance of the terms and conditions these terms, Apple will have the right (and will be deemed to have accepted the right) to apply these terms in relation to its license application originating from the App Store against you as a third party beneficiary thereof.
    Without limiting any other terms of these terms, you must comply with all applicable third party terms of agreement when using the originating application in the App Store.

    <h4>Migohood content and content license of members.</h4>
    Subject to compliance with the terms and conditions of these terms, Migohood granted a limited non-exclusive, non-transferable license to access and view any content Migohood exclusively for personal and non-commercial purposes and access and view any content that is member allowing access solely for your personal and non-commercial purposes. You have no right to sublicense the license rights granted in this section.
    You will not use, copy, adapt, modify, prepare derivative works, distribute, license, sell, transfer, display publicly, publicly perform, transmit, broadcast or in any other way will explode the website, application, services or collective contents except as expressly permitted in these terms. You will not grant any license or right to you by implication or otherwise under any intellectual property rights owned by Migohood or its licensors, or under its control except licenses and rights expressly granted in these terms.

    <h4>Member Content.</h4>
    We may, in our sole discretion, allow you to republish, upload, post, display or transmit content for members. By making available any Member Content on or through the website, application and services, you hereby grant Migohood a worldwide, irrevocable, perpetual (or the term of protection), non-exclusive, transferable, royalty free license royalties, with the right to sublicense, to use, display, copy, adapt, modify, distribute, license, sell, transfer, publicly display, publicly perform, transmit, download continuously, broadcast, access, display and otherwise exploit Membership in such content, through or through the website, application and services or to promote or market. Migohood not claim any ownership rights in such content and no member of these terms are deemed to restrict those rights you may have to use and exploit such Member Content.
    You acknowledge and agree that you are solely responsible for the content of member to make available through the web site, application and services. Consequently, you represent and warrant that: You are the sole and exclusive owner of all content of member to make available through the web site, application and services or you have all rights, licenses, consents and releases that They are necessary to grant the rights Migohood membership of such content, as provided under these terms; and neither the member nor its content posting, uploading, hang up, delivery or transmission of the content of member or your use of the content of Migohood member, through, or through the web site, application and services infringes, will appropriate or infringe the patent, copyright, trademark, trade secret or moral rights of third parties or other proprietary rights or intellectual property rights or rights of publicity or privacy, or will result in the violation of any law or regulation applicable.

    <h4>Links</h4>
    The Web site, application and services can contain links to websites or third party resources. You acknowledge and agree that Migohood is not responsible or subject to: the availability or accuracy of such websites or resources; or the content, products, or services on or available on such websites or resources. Links to such websites or resources do not imply any endorsement by Migohood to such websites or resources to content, products or services available from such websites or resources. You accept sole responsibility for and assume all risk arising from your use of such websites or resources or the content, products, or services on or available on such websites or resources.
    Some parts of the platform operated Migohood geographic location services Google Maps or Google Earth, including application programming interfaces (API) of Google Maps. The your use of Google Maps or Google Earth is subject to the terms of use of Google.

    <h4>Proprietary rights notices</h4>

    All trademarks, service marks, logos, trade names and other proprietary designation Migohood used herein are registered trademarks or trademarks of Migohood. Any other trademark, service mark, logo, trademark and other proprietary designations are either registered trademarks or trademarks of their respective owners.

    <h4>Reviews</h4>

    We thank you and encourage you to provide comments, opinions and suggestions to improve the site, application and services can send comments by mail, through the website and the application, or other media. You acknowledge and agree that all comments that you send us will be sole property of Migohood and hereby irrevocably assign and agree to assign to Migohood irrevocably Migohood all rights, title and interest in all comments, including without limitation all patent rights, copyrights, trade secrets, moral rights and other intellectual property rights included, and waive any moral rights you may have on these comments. Upon request of Migohood and running Migohood the costs, will sign documents and give more steps as may reasonably request to help Migohood Migohood to acquire, develop and maintain its intellectual property rights and other legal protections for comments.

    <h4>Copyright policy.</h4>
    Migohood respects copyright law and expects its users to do the same. It is the policy of Migohood cease and terminate in appropriate circumstances Migohood accounts of other users and account holders who repeatedly infringe or are believed to have repeatedly violated the rights of the holders of the copyright.

    <h4>Suspension, termination and cancellation Migohood account.</h4>
    We may, at our discretion and without liability to you, with or without cause, with or without notice at any time decide to limit, suspend, disable or terminate your account Migohood. If we exercise this right under these terms, all or any of the consequences listed below may take place with or without notice or explanation to you: your account Migohood it is disabled or stopped, your password will be disabled, and can not they access the Web page, application, our services, your account Migohood or its contents member, or assistance from customer service Migohood, all outstanding future bookings or accepted, either as a user or customer, will immediately canceled, we can communicate to your users or customers who have canceled a potential reserve or confirmed, we will fully reimburse customers all confirmed bookings, regardless of the policies of preexisting cancellation, we will contact customers to inform them about possible alternative accommodation with others that may be available on the web site, application and services and in the same manner for the provision of services, and you will not be entitled to any compensation for the reserves (including confirmed) that were canceled as consequence of a suspension, deactivation or termination of your account Migohood. You can cancel your account at any time Migohood or emailing. Note that if you cancel your account Migohood, we have no obligation to remove or return any content that is published on the website, application and services, including, among all other criticism or comment.

    <h4>Disclaimers.</h4>
    If you decide to use the website, application, services or content groups, you do so at your own risk, exclusively. You acknowledge and agree that Migohood has no obligation to perform background checks or sexual assault of any member, including among others, users and customers but may perform such background checks or sexual assault if it considers Migohood. The website, application, services, contents are provided without warranty of any kind, either express or implied. Without limiting the foregoing, Migohood expressly disclaims all warranties of merchantability, fitness for a particular purpose, use, enjoyment or exemption from infringement and any warranty arising from course of dealing or usage of the transaction, Migohood offers no guarantee that the page web, application, services, content, including, among others, the offers of accommodation or service will meet your requirements or be available on an uninterrupted, secure and error-free manner.
    Migohood no warranty on the quality of the offers of accommodation or provision of services, users, customers, credit accumulation or service accommodation, services or content, or accuracy, timeliness, credibility, completeness or reliability of any Content that is obtained through the website, application services or accommodations or service credits.
    No advice or information, whether oral or written, which is obtained by Migohood or through the website, application, services or content constitute any warranty, express or implied.
    You are solely responsible for all communications and interactions with other users of the website, application or services and others with whom you communicate or interact as a result of using the website, application or services, including users and customers and others.
    You understand that Migohood makes no attempt to verify the statements of users of the website, application or service, or to check or visit any accommodation or verify the provision of a service. Migohood makes no warranties or representations as to the behavior of users of the website, application or services, or their compatibility with any current or future user of the website, application or services.
    You agree to take reasonable precautions in all communications and interactions with other users of the website, application or services, and others to communicate or interact as a result of your use of the website, application or services, including users and customers among others, especially if you decide to meet outside internet or personally, regardless of whether these meetings are organized by Migohood. Without prejudice to the appointment of an agent Migohood limited collections d users in order to accept payments from customers on behalf of users, Migohood expressly declares that no liability for the acts or omissions of users with regard customers or third parties, and so you accept it.

    <h4>Disclaimer</h4>
    You agree that to the extent permitted by law, you assume all risks associated with its access and use of the website, application, services and content, offers accommodation or service, subject to any property or service; as well as any contact you have with other users of Migohood, either in person or online, or Migohood nor any other party involved in creating, producing or delivering the website, application, services, content will be liable for any incidental, special, exemplary or consequential damages, including lost profits, loss of data or loss of goodwill, business interruption, computer damage or system failure, or the cost of products or services of substitution, or any person harm, bodily injury or emotional distress arising out of these terms or is linked to, and arising from the use of or inability to use the website, application, services, or others with whom you communicate or interact as a result of your use of the website, application, services, publications or reservations of accommodation and services through the web site, application and services Migohood, whether based on warranty, contract , tort, product liability or any other legal theory, and whether or not Migohood informed of the possibility of such damage, even if it is stated that a limited legal recourse failed.

    <h4>Compensation</h4>
    You agree to release, defend, indemnify and hold harmless Migohood and its affiliates and subsidiaries, and their officers, directors, employees and agents from all claims, liabilities, damages, losses and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected to your access or use of the website, application, services, collective content or your violation of these terms; Membership contents; interaction with any member, or an accommodation booking service or the publication of a housing or service; use, condition or rental of accommodation for its part, including, among others, any injuries, losses or damages (compensatory, direct, incidental, consequential or otherwise) of any kind arising in connection with or as a result of , rent, reserve or use a housing or providing a service, and accumulation of credits Migohood accommodation or service.

    <h4>Export Control and countries with restrictions</h4>
    You may not use, export, re-export, import or transfer the application, except as may be permitted by the laws of the United States, the laws of the jurisdiction in which the application has been obtained and any other applicable law. In particular, but without limitation, the application can not be exported or re-exported: to countries subject to US embargoes; or persons on the list of Specially Designated Treasury of the United States. UU. or Denied Parties List Department of Commerce US. UU. By using the site, application and services, you represent and warrant that neither you nor your accommodation is located in a country embargoed by the US Government. UU. Or who has been designated by the US Government. UU. as a country "supports terrorism" and not on any list of prohibited or restricted parties. UU.

    <h4>Assignment</h4>
    You may not assign or transfer these terms, by operation of law or any other way, without the prior written consent of Migohood. Any attempt by you to assign or transfer Migohood terms, without such consent will be void and have no effect. Migohood may assign or transfer these Terms, in its sole discretion and without restriction. In accordance with the above, these terms will be binding and strengthen the benefits of the parties, their successors and permitted assigns.

    <h4>Notices</h4>
    All notices or other communications permitted or required by this, including those regarding changes to these terms shall be in writing and provide Migohood through the mail (in each case to the address you provide) or with a publication website or through the application. For announcements made by mail, the date of dispatch will be the date on which such notice is transmitted.

    <h4>Control law and jurisdiction</h4>
    These terms and your use of services shall be construed in accordance with the laws of the United States of America, regardless of conflict of law provisions.

    <h4>Settlement of disputes</h4>
    And Migohood you agree that any dispute, controversy or claim referred or related to these terms, or the breach, termination, execution, interpretation or termination thereof, or the use of services or use of the website or application They shall be settled by binding arbitration, although each party reserves the right to seek injunctive or equitable relief in a court of competent jurisdiction to prevent the infringement, misappropriation or violation of copyrights, trademarks, trade secrets, patents or other intellectual property and the threat that they occur. You acknowledge and agree that you and Migohood waive the right to trial by jury or to participate as a plaintiff or set a trial member joint action or a representative procedure. Also, unless you and Migohood agree otherwise in writing, the arbitrator may not consolidate the demands of more than one person and can not preside over any joint action or representative proceeding. In the event that this particular paragraph was inapplicable, it is considered void this entire section of "dispute resolution". Except as provided in the preceding sentence, this section of "dispute resolution" will remain in force even after the termination of these terms.

    <h4>Arbitration rules and applicable law.</h4>
    The arbitration shall be administered by the American Arbitration Association (American Arbitration Association, "AAA") in accordance with the commercial arbitration rules and complementary procedures for disputes relating to consumers that apply, except to the extent modified by This section litigation. The Federal Arbitration Act the interpretation and application of this section in the United States. In the case of Colombia it was held in the centers of Arbitration of the Chamber of Commerce of Santa Marta (Magdalena). And other countries are held in the respective arbitration centers. You agree that these centers will be in litigation or arbitration where legal disputes are resolved and not elsewhere.
    Arbitration process. If a party wishes to initiate arbitration, it must provide the other party a written request for arbitration as stipulated by the rules of the AAA (The AAA makes an application for arbitration and a separate form for residents in the State of California). It may act as arbitrator a retired both as a licensed attorney judge, and will be chosen by the parties from among the arbitrators who appear on the list of referees for consumer disputes AAA in the case of US. If the parties fail to agree on the choice of referee after seven (7) days after delivery of the request for arbitration, the AAA appoint the arbitrator under AAA rules
    Place and arbitration. Unless you and Migohood decide otherwise, the arbitration shall be conducted in their place of residence. If your claim does not exceed 10 000 USD, the arbitration shall be conducted exclusively from the documents you provide to the referee and Migohood unless you request a hearing or that he considers that a hearing is necessary. If your claim exceeds $ 10 000, their right to a hearing in accordance with the rules of the AAA will be determined Subject to the rules of the AAA, the arbitrator may, at its discretion, conduct a reasonable exchange of information between the parties, which is consistent with the expedited nature of arbitration.
    The arbitrator's decision. The arbitrator shall render an award within the period stipulated by the rules of the AAA The arbitrator's decision will include the results and key findings on which it based the award. This can be entered as a judgment in any court of competent jurisdiction. The compensation for damages determined by the arbitrator shall be consistent with the provisions above in the section "Disclaimer", in regard to the type and amount of damages that may be responsible for one of the parties and likewise in the case of disputes that Colombia and other countries are resolved. The arbitrator may issue an order for redress of grievances or protective only for the plaintiff and only in so far as necessary to provide redress to individual demand justified the complainant.

    <h4>Changes regarding the settlement of disputes.</h4>
    Notwithstanding other provisions of these terms, if Migohood amending its section on "Dispute" after the date on which you have initially accepted these terms (or has accepted any subsequent modification of these terms), you can refuse such change by sending a written notice (also valid email) within 30 days from the date of entry into force of the change, as indicated in the "Date Last Modified" previously mentioned or date the last email Migohood has sent the notification of the change. In rejecting any changes, you accept the arbitration of any dispute arising between you and Migohood accordance with the provisions of this section "Dispute" from the date of acceptance of these terms (or acceptance of any modification Rear of these Terms).

    <h4>Overview</h4>
    That is not availed by Migohood of any right or provision in these Terms does not constitute a waiver of the future use of such right or provision. A waiver of such right or provision shall be effective only if made in writing and signed by a duly authorized representative of Migohood. Unless stipulated explicitly in these terms, the filing by either party of any of the resources that belong under these terms shall be without prejudice to other forms of reparation that apply under these terms or otherwise. If for any reason an arbitrator or a court of competent jurisdiction determines that any provision of these terms is invalid or can not be applied, that provision will be applied in all the permissible and the other provisions of these terms remain in implementation and effects complete.
    These terms do not provide and are not intended to confer any rights to other persons other than the parties. Notwithstanding the foregoing, the parties agree that the payment card networks are third party beneficiaries of these terms for the purposes of enforcing the provisions on payments, but their consent or agreement is not required for any change or modification of these terms.
    These Terms constitute the complete and exclusive understanding and agreement between you and Migohood on the website, application, services, collective contents and any reservations or list of accommodations and services made through the web site, application and services . For all purposes must differentiate between the services they provide users and services provided Migohood.

    <br><br><strong>* On any questions about these terms and conditions, you can contact Migohood.</strong>

  </div>
</div>



@stop
